/*
 * Copyright © 2025 anyilanxin zxh(anyilanxin@aliyun.com)
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

/**
 * WARNING
 *
 * The lib file is auto-generated by the `compile:builtins` (or `update:builtins`) task.
 *
 * Make sure you edit the template file `tasks/kunpengBuiltins.template.js` and run `compile:builtins` (or `update:builtins`) to update the file in lib.
 */

/**
 * @typedef { {
 *   name: string,
 *   info: string,
 *   type?: 'function',
 *   params?: Array<{
 *     name: string;
 *   }>,
 *   engines?: Record<string, string>
 * } } Builtin
 */

/**
 * List of standard FEEL built-in functions (excluding Camunda-specific extensions).
 *
 * @type { Builtin[] }
 */
export const qlexpressionBuiltins = [
  {
    'name': 'not',
    'type': 'function',
    'params': [
      {
        'name': 'negand'
      }
    ],
    'info': '<p>Returns the logical negation of the given value.</p>\n<p><strong>Function signature</strong></p>\n<pre><code class="language-qlexpression">not(negand: boolean): boolean\n</code></pre>\n<p><strong>Examples</strong></p>\n<pre><code class="language-qlexpression">not(true)\n// false\n\nnot(null)\n// null\n</code></pre>\n'
  },
  {
    'name': 'in',
    'type': 'function',
    'params': [
      {
        'name': 'negand'
      }
    ],
    'info': '<p>Returns the logical negation of the given value.</p>\n<p><strong>Function signature</strong></p>\n<pre><code class="language-qlexpression">in(negand: boolean): boolean\n</code></pre>\n<p><strong>Examples</strong></p>\n<pre><code class="language-qlexpression">in(true)\n// true\n\nin(null)\n// null\n</code></pre>\n'
  },
  {
    'name': 'getValue',
    'type': 'function',
    'params': [
      {
        'name': 'context'
      },
      {
        'name': 'key'
      }
    ],
    'info': '<p>Returns the value of the context entry with the given key.</p>\n<p><strong>Function signature</strong></p>\n<pre><code class="language-qlexpression">getValue(context: context, key: string): Any\n</code></pre>\n<p><strong>Examples</strong></p>\n<pre><code class="language-qlexpression">getValue({foo: 123}, &quot;foo&quot;)\n// 123\n\ngetValue({a: 1}, &quot;b&quot;)\n// null\n</code></pre>\n'
  },
  {
    'name': 'getEntries',
    'type': 'function',
    'params': [
      {
        'name': 'context'
      }
    ],
    'info': '<p>Returns the entries of the context as a list of key-value-pairs.</p>\n<p><strong>Function signature</strong></p>\n<pre><code class="language-qlexpression">getEntries(context: context): list&lt;context&gt;\n</code></pre>\n<p>The return value is a list of contexts. Each context contains two entries for &quot;key&quot; and &quot;value&quot;.</p>\n<p><strong>Examples</strong></p>\n<pre><code class="language-qlexpression">getEntries({foo: 123})\n// [{key: &quot;foo&quot;, value: 123}]\n</code></pre>\n'
  },
  {
    'name': 'contextPut',
    'type': 'function',
    'params': [
      {
        'name': 'context'
      },
      {
        'name': 'keys'
      },
      {
        'name': 'value'
      }
    ],
    'info': '<p>Adds a new entry with the given value to the context. The path of the entry is defined by the keys. Returns a new context that includes the entry.</p>\n<p>If <code>keys</code> contains the keys <code>[k1, k2]</code> then it adds the nested entry <code>k1.k2 = value</code> to the context.</p>\n<p>If an entry for the same keys already exists in the context, it overrides the value.</p>\n<p>If <code>keys</code> are empty, it returns <code>null</code>.</p>\n<p><strong>Function signature</strong></p>\n<pre><code class="language-qlexpression">contextPut(context: context, keys: list&lt;string&gt;, value: Any): context\n</code></pre>\n<p><strong>Examples</strong></p>\n<pre><code class="language-qlexpression">contextPut({x:1}, [&quot;y&quot;], 2)\n// {x:1, y:2}\n\ncontextPut({x:1, y: {z:0}}, [&quot;y&quot;, &quot;z&quot;], 2)\n// {x:1, y: {z:2}}\n\ncontextPut({x:1}, [&quot;y&quot;, &quot;z&quot;], 2)\n// {x:1, y: {z:2}}\n</code></pre>\n'
  },
  {
    'name': 'string',
    'type': 'function',
    'params': [
      {
        'name': 'from'
      }
    ],
    'info': '<p>Returns the given value as a string representation.</p>\n<p><strong>Function signature</strong></p>\n<pre><code class="language-qlexpression">string(from: Any): string\n</code></pre>\n<p><strong>Examples</strong></p>\n<pre><code class="language-qlexpression">string(1.1)\n// &quot;1.1&quot;\n\nstring(date(&quot;2012-12-25&quot;))\n// &quot;2012-12-25&quot;\n</code></pre>\n'
  },
  {
    'name': 'number',
    'type': 'function',
    'params': [
      {
        'name': 'from'
      }
    ],
    'info': '<p>Parses the given string to a number.</p>\n<p>Returns <code>null</code> if the string is not a number.</p>\n<p><strong>Function signature</strong></p>\n<pre><code class="language-qlexpression">number(from: string): number\n</code></pre>\n<p><strong>Examples</strong></p>\n<pre><code class="language-qlexpression">number(&quot;1500.5&quot;)\n// 1500.5\n</code></pre>\n'
  },
  {
    'name': 'number',
    'type': 'function',
    'params': [
      {
        'name': 'from'
      },
      {
        'name': 'grouping separator'
      }
    ],
    'info': '<p>Parses the given string to a number using the specified grouping separator.</p>\n<p>Returns <code>null</code> if the string is not a number.</p>\n<p><strong>Function signature</strong></p>\n<pre><code class="language-qlexpression">number(from: string, grouping separator: string): number\n</code></pre>\n<p><strong>Examples</strong></p>\n<pre><code class="language-qlexpression">number(&quot;1,500&quot;, &quot;,&quot;)\n// 1500\n</code></pre>\n'
  },
  {
    'name': 'number',
    'type': 'function',
    'params': [
      {
        'name': 'from'
      },
      {
        'name': 'grouping separator'
      },
      {
        'name': 'decimal separator'
      }
    ],
    'info': '<p>Parses the given string to a number using the specified grouping and decimal separators.</p>\n<p>Returns <code>null</code> if the string is not a number.</p>\n<p><strong>Function signature</strong></p>\n<pre><code class="language-qlexpression">number(from: string, grouping separator: string, decimal separator: string): number\n</code></pre>\n<p><strong>Examples</strong></p>\n<pre><code class="language-qlexpression">number(&quot;1 500.5&quot;, &quot; &quot;, &quot;.&quot;)\n// 1500.5\n</code></pre>\n'
  },
  {
    'name': 'context',
    'type': 'function',
    'params': [
      {
        'name': 'entries'
      }
    ],
    'info': '<p>Constructs a context of the given list of key-value pairs. It is the reverse function to <a href="feel-built-in-functions-context.md#get-entriescontext">getEntries()</a>.</p>\n<p>Each key-value pair must be a context with two entries: <code>key</code> and <code>value</code>. The entry with name <code>key</code> must have a value of the type <code>string</code>.</p>\n<p>It might override context entries if the keys are equal. The entries are overridden in the same order as the contexts in the given list.</p>\n<p>Returns <code>null</code> if one of the entries is not a context or if a context doesn&#39;t contain the required entries.</p>\n<p><strong>Function signature</strong></p>\n<pre><code class="language-qlexpression">context(entries: list&lt;context&gt;): context\n</code></pre>\n<p><strong>Examples</strong></p>\n<pre><code class="language-qlexpression">context([{&quot;key&quot;:&quot;a&quot;, &quot;value&quot;:1}, {&quot;key&quot;:&quot;b&quot;, &quot;value&quot;:2}])\n// {a:1, b:2}\n</code></pre>\n'
  },
  {
    'name': 'date',
    'type': 'function',
    'params': [
      {
        'name': 'from'
      }
    ],
    'info': '<p>Returns a date from the given value.</p>\n<p>Returns <code>null</code> if the string is not a valid calendar date. For example, <code>&quot;2024-06-31&quot;</code> is invalid because June has\nonly 30 days.</p>\n<p><strong>Function signature</strong></p>\n<pre><code class="language-qlexpression">date(from: string): date\n</code></pre>\n<p>Parses the given string into a date.</p>\n<pre><code class="language-qlexpression">date(from: date and time): date\n</code></pre>\n<p>Extracts the date component from the given date and time.</p>\n<p><strong>Examples</strong></p>\n<pre><code class="language-qlexpression">date(&quot;2018-04-29&quot;)\n// date(&quot;2018-04-29&quot;)\n\ndate(dateTime(&quot;2012-12-25T11:00:00&quot;))\n// date(&quot;2012-12-25&quot;)\n</code></pre>\n'
  },
  {
    'name': 'date',
    'type': 'function',
    'params': [
      {
        'name': 'year'
      },
      {
        'name': 'month'
      },
      {
        'name': 'day'
      }
    ],
    'info': '<p>Returns a date from the given components.</p>\n<p>Returns <code>null</code> if the components don&#39;t represent a valid calendar date. For example, <code>2024,6,31</code> is invalid because\nJune has only 30 days.</p>\n<p><strong>Function signature</strong></p>\n<pre><code class="language-qlexpression">date(year: number, month: number, day: number): date\n</code></pre>\n<p><strong>Examples</strong></p>\n<pre><code class="language-qlexpression">date(2012, 12, 25)\n// date(&quot;2012-12-25&quot;)\n</code></pre>\n'
  },
  {
    'name': 'time',
    'type': 'function',
    'params': [
      {
        'name': 'from'
      }
    ],
    'info': '<p>Returns a time from the given value.</p>\n<p><strong>Function signature</strong></p>\n<pre><code class="language-qlexpression">time(from: string): time\n</code></pre>\n<p>Parses the given string into a time.</p>\n<pre><code class="language-qlexpression">time(from: date and time): time\n</code></pre>\n<p>Extracts the time component from the given date and time.</p>\n<p><strong>Examples</strong></p>\n<pre><code class="language-qlexpression">time(&quot;12:00:00&quot;)\n// time(&quot;12:00:00&quot;)\n\ntime(dateTime(&quot;2012-12-25T11:00:00&quot;))\n// time(&quot;11:00:00&quot;)\n</code></pre>\n'
  },
  {
    'name': 'time',
    'type': 'function',
    'params': [
      {
        'name': 'hour'
      },
      {
        'name': 'minute'
      },
      {
        'name': 'second'
      }
    ],
    'info': '<p>Returns a time from the given components.</p>\n<p><strong>Function signature</strong></p>\n<pre><code class="language-qlexpression">time(hour: number, minute: number, second: number): time\n</code></pre>\n<p><strong>Examples</strong></p>\n<pre><code class="language-qlexpression">time(23, 59, 0)\n// time(&quot;23:59:00&quot;)\n</code></pre>\n'
  },
  {
    'name': 'time',
    'type': 'function',
    'params': [
      {
        'name': 'hour'
      },
      {
        'name': 'minute'
      },
      {
        'name': 'second'
      },
      {
        'name': 'offset'
      }
    ],
    'info': '<p>Returns a time from the given components, including a timezone offset.</p>\n<p><strong>Function signature</strong></p>\n<pre><code class="language-qlexpression">time(hour: number, minute: number, second: number, offset: days and time duration): time\n</code></pre>\n<p><strong>Examples</strong></p>\n<pre><code class="language-qlexpression">time(14, 30, 0, duration(&quot;PT1H&quot;))\n// time(&quot;14:30:00+01:00&quot;)\n</code></pre>\n'
  },
  {
    'name': 'dateTime',
    'type': 'function',
    'params': [
      {
        'name': 'from'
      }
    ],
    'info': '<p>Parses the given string into a date and time. The function supports strings in the format <code>YYYY-MM-DDThh:mm:ss</code> with\noptional timezone information either as offset (e.g., <code>+01:00</code> or <code>Z</code>), as IANA timezone ID (e.g., <code>@Europe/Berlin</code>), or\nas a combination of both (e.g., <code>+01:00[Europe/Berlin]</code>).</p>\n<p>Returns <code>null</code> if the string is not a valid calendar date. For example, <code>&quot;2024-06-31T10:00:00&quot;</code> is invalid because\nJune has only 30 days.</p>\n<p><strong>Function signature</strong></p>\n<pre><code class="language-qlexpression">dateTime(from: string): date and time\n</code></pre>\n<p><strong>Examples</strong></p>\n<pre><code class="language-qlexpression">dateTime(&quot;2018-04-29T09:30:00&quot;)\n// dateTime(&quot;2018-04-29T09:30:00&quot;)\n\ndateTime(&quot;2018-04-29T09:30:00+02:00&quot;)\n// dateTime(&quot;2018-04-29T09:30:00+02:00&quot;)\n\ndateTime(&quot;2018-04-29T09:30:00@Europe/Berlin&quot;)\n// dateTime(&quot;2018-04-29T09:30:00@Europe/Berlin&quot;)\n\ndateTime(&quot;2018-04-29T09:30:00+02:00[Europe/Berlin]&quot;)\n// dateTime(&quot;2018-04-29T09:30:00@Europe/Berlin&quot;)\n</code></pre>\n'
  },
  {
    'name': 'dateTime',
    'type': 'function',
    'params': [
      {
        'name': 'date'
      },
      {
        'name': 'time'
      }
    ],
    'info': '<p>Returns a date and time from the given components.</p>\n<p><strong>Function signature</strong></p>\n<pre><code class="language-qlexpression">dateTime(date: date, time: time): date and time\n</code></pre>\n<pre><code class="language-qlexpression">dateTime(date: date and time, time: time): date and time\n</code></pre>\n<p>Returns a date and time value that consists of the date component of <code>date</code> combined with <code>time</code>.</p>\n<p><strong>Examples</strong></p>\n<pre><code class="language-qlexpression">dateTime(date(&quot;2012-12-24&quot;),time(&quot;T23:59:00&quot;))\n// dateTime(&quot;2012-12-24T23:59:00&quot;)\n\ndateTime(dateTime(&quot;2012-12-25T11:00:00&quot;),time(&quot;T23:59:00&quot;))\n// dateTime(&quot;2012-12-25T23:59:00&quot;)\n</code></pre>\n'
  },
  {
    'name': 'duration',
    'type': 'function',
    'params': [
      {
        'name': 'from'
      }
    ],
    'info': '<p>Parses the given string into a duration. The duration is either a days and time duration or a years and months duration.</p>\n<p><strong>Function signature</strong></p>\n<pre><code class="language-qlexpression">duration(from: string): days and time duration\n</code></pre>\n<pre><code class="language-qlexpression">duration(from: string): years and months duration\n</code></pre>\n<p><strong>Examples</strong></p>\n<pre><code class="language-qlexpression">duration(&quot;P5D&quot;)\n// duration(&quot;P5D&quot;)\n\nduration(&quot;P32Y&quot;)\n// duration(&quot;P32Y&quot;)\n</code></pre>\n'
  },
  {
    'name': 'yearsAndMonthsDuration',
    'type': 'function',
    'params': [
      {
        'name': 'from'
      },
      {
        'name': 'to'
      }
    ],
    'info': '<p>Returns the years and months duration between <code>from</code> and <code>to</code>.</p>\n<p><strong>Function signature</strong></p>\n<pre><code class="language-qlexpression">yearsAndMonthsDuration(from: date, to: date): years and months duration\n</code></pre>\n<p><strong>Examples</strong></p>\n<pre><code class="language-qlexpression">yearsAndMonthsDuration(date(&quot;2011-12-22&quot;), date(&quot;2013-08-24&quot;))\n// duration(&quot;P1Y8M&quot;)\n</code></pre>\n'
  },
  {
    'name': 'fromJson',
    'type': 'function',
    'params': [
      {
        'name': 'value'
      }
    ],
    'info': '<p>Parses a JSON string into a FEEL value. The function converts JSON primitives, objects, and arrays into their corresponding FEEL types.</p>\n<p>Returns <code>null</code> if the string is not a valid JSON value.</p>\n<p><strong>Function signature</strong></p>\n<pre><code class="language-qlexpression">fromJson(value: string): Any\n</code></pre>\n<p><strong>Examples</strong></p>\n<pre><code class="language-qlexpression">fromJson(&quot;{\\&quot;a\\&quot;: 1, \\&quot;b\\&quot;: 2}&quot;)\n// {a: 1, b: 2}\n\nfromJson(&quot;true&quot;)\n// true\n\nfromJson(&quot;\\&quot;2023-06-14\\&quot;&quot;)\n// &quot;2023-06-14&quot;\n</code></pre>\n',
    'engines': {
      'kunpeng': '>=8.9'
    }
  },
  {
    'name': 'toJson',
    'type': 'function',
    'params': [
      {
        'name': 'value'
      }
    ],
    'info': '<p>Converts a FEEL value into a JSON string. The function converts FEEL primitives, contexts, and lists into their\ncorresponding JSON types. Temporal values are converted to their ISO 8601 string representation, including timezone\ninformation for date and time values (format: <code>2025-11-24T10:00:00+01:00[Europe/Berlin]</code>).</p>\n<p><strong>Function signature</strong></p>\n<pre><code class="language-qlexpression">toJson(value: Any): string\n</code></pre>\n<p><strong>Examples</strong></p>\n<pre><code class="language-qlexpression">toJson({a: 1, b: 2})\n// &quot;{\\&quot;a\\&quot;:1,\\&quot;b\\&quot;:2}&quot;\n\ntoJson(true)\n// &quot;true&quot;\n\ntoJson(@&quot;2023-06-14&quot;)\n// &quot;\\&quot;2023-06-14\\&quot;&quot;\n\ntoJson(@&quot;2025-11-24T10:00:00@Europe/Berlin&quot;)\n// &quot;\\&quot;2025-11-24T10:00:00+01:00[Europe/Berlin]\\&quot;&quot;\n\ntoJson(@&quot;P3Y&quot;)\n// &quot;\\&quot;P3Y\\&quot;&quot;\n</code></pre>\n',
    'engines': {
      'kunpeng': '>=8.9'
    }
  },
  {
    'name': 'listContains',
    'type': 'function',
    'params': [
      {
        'name': 'list'
      },
      {
        'name': 'element'
      }
    ],
    'info': '<p>Returns <code>true</code> if the given list contains the element. Otherwise, returns <code>false</code>.</p>\n<p><strong>Function signature</strong></p>\n<pre><code class="language-qlexpression">listContains(list: list, element: Any): boolean\n</code></pre>\n<p><strong>Examples</strong></p>\n<pre><code class="language-qlexpression">listContains([1,2,3], 2)\n// true\n</code></pre>\n'
  },
  {
    'name': 'count',
    'type': 'function',
    'params': [
      {
        'name': 'list'
      }
    ],
    'info': '<p>Returns the number of elements of the given list.</p>\n<p><strong>Function signature</strong></p>\n<pre><code class="language-qlexpression">count(list: list): number\n</code></pre>\n<p><strong>Examples</strong></p>\n<pre><code class="language-qlexpression">count([1,2,3])\n// 3\n</code></pre>\n'
  },
  {
    'name': 'min',
    'type': 'function',
    'params': [
      {
        'name': 'list'
      }
    ],
    'info': '<p>Returns the minimum of the given list.</p>\n<p><strong>Function signature</strong></p>\n<pre><code class="language-qlexpression">min(list: list): Any\n</code></pre>\n<p>All elements in <code>list</code> should have the same type and be comparable.</p>\n<p>The parameter <code>list</code> can be passed as a list or as a sequence of elements.</p>\n<p><strong>Examples</strong></p>\n<pre><code class="language-qlexpression">min([1,2,3])\n// 1\n\nmin(1,2,3)\n// 1\n</code></pre>\n'
  },
  {
    'name': 'max',
    'type': 'function',
    'params': [
      {
        'name': 'list'
      }
    ],
    'info': '<p>Returns the maximum of the given list.</p>\n<p><strong>Function signature</strong></p>\n<pre><code class="language-qlexpression">max(list: list): Any\n</code></pre>\n<p>All elements in <code>list</code> should have the same type and be comparable.</p>\n<p>The parameter <code>list</code> can be passed as a list or as a sequence of elements.</p>\n<p><strong>Examples</strong></p>\n<pre><code class="language-qlexpression">max([1,2,3])\n// 3\n\nmax(1,2,3)\n// 3\n</code></pre>\n'
  },
  {
    'name': 'sum',
    'type': 'function',
    'params': [
      {
        'name': 'list'
      }
    ],
    'info': '<p>Returns the sum of the given list of numbers.</p>\n<p><strong>Function signature</strong></p>\n<pre><code class="language-qlexpression">sum(list: list&lt;number&gt;): number\n</code></pre>\n<p>The parameter <code>list</code> can be passed as a list or as a sequence of elements.</p>\n<p><strong>Examples</strong></p>\n<pre><code class="language-qlexpression">sum([1,2,3])\n// 6\n\nsum(1,2,3)\n// 6\n</code></pre>\n'
  },
  {
    'name': 'product',
    'type': 'function',
    'params': [
      {
        'name': 'list'
      }
    ],
    'info': '<p>Returns the product of the given list of numbers.</p>\n<p><strong>Function signature</strong></p>\n<pre><code class="language-qlexpression">product(list: list&lt;number&gt;): number\n</code></pre>\n<p>The parameter <code>list</code> can be passed as a list or as a sequence of elements.</p>\n<p><strong>Examples</strong></p>\n<pre><code class="language-qlexpression">product([2, 3, 4])\n// 24\n\nproduct(2, 3, 4)\n// 24\n</code></pre>\n'
  },
  {
    'name': 'mean',
    'type': 'function',
    'params': [
      {
        'name': 'list'
      }
    ],
    'info': '<p>Returns the arithmetic mean (i.e. average) of the given list of numbers.</p>\n<p><strong>Function signature</strong></p>\n<pre><code class="language-qlexpression">mean(list: list&lt;number&gt;): number\n</code></pre>\n<p>The parameter <code>list</code> can be passed as a list or as a sequence of elements.</p>\n<p><strong>Examples</strong></p>\n<pre><code class="language-qlexpression">mean([1,2,3])\n// 2\n\nmean(1,2,3)\n// 2\n</code></pre>\n'
  },
  {
    'name': 'median',
    'type': 'function',
    'params': [
      {
        'name': 'list'
      }
    ],
    'info': '<p>Returns the median element of the given list of numbers.</p>\n<p><strong>Function signature</strong></p>\n<pre><code class="language-qlexpression">median(list: list&lt;number&gt;): number\n</code></pre>\n<p>The parameter <code>list</code> can be passed as a list or as a sequence of elements.</p>\n<p><strong>Examples</strong></p>\n<pre><code class="language-qlexpression">median(8, 2, 5, 3, 4)\n// 4\n\nmedian([6, 1, 2, 3])\n// 2.5\n</code></pre>\n'
  },
  {
    'name': 'stddev',
    'type': 'function',
    'params': [
      {
        'name': 'list'
      }
    ],
    'info': '<p>Returns the standard deviation of the given list of numbers.</p>\n<p><strong>Function signature</strong></p>\n<pre><code class="language-qlexpression">stddev(list: list&lt;number&gt;): number\n</code></pre>\n<p>The parameter <code>list</code> can be passed as a list or as a sequence of elements.</p>\n<p><strong>Examples</strong></p>\n<pre><code class="language-qlexpression">stddev(2, 4, 7, 5)\n// 2.0816659994661326\n\nstddev([2, 4, 7, 5])\n// 2.0816659994661326\n</code></pre>\n'
  },
  {
    'name': 'mode',
    'type': 'function',
    'params': [
      {
        'name': 'list'
      }
    ],
    'info': '<p>Returns the mode of the given list of numbers.</p>\n<p><strong>Function signature</strong></p>\n<pre><code class="language-qlexpression">mode(list: list&lt;number&gt;): number\n</code></pre>\n<p>The parameter <code>list</code> can be passed as a list or as a sequence of elements.</p>\n<p><strong>Examples</strong></p>\n<pre><code class="language-qlexpression">mode(6, 3, 9, 6, 6)\n// [6]\n\nmode([6, 1, 9, 6, 1])\n// [1, 6]\n</code></pre>\n'
  },
  {
    'name': 'all',
    'type': 'function',
    'params': [
      {
        'name': 'list'
      }
    ],
    'info': '<p>Returns <code>false</code> if any element of the given list is <code>false</code>. Otherwise, returns <code>true</code>.</p>\n<p>If the given list is empty, it returns <code>true</code>.</p>\n<p><strong>Function signature</strong></p>\n<pre><code class="language-qlexpression">all(list: list&lt;boolean&gt;): boolean\n</code></pre>\n<p>The parameter <code>list</code> can be passed as a list or as a sequence of elements.</p>\n<p><strong>Examples</strong></p>\n<pre><code class="language-qlexpression">all([true,false])\n// false\n\nall(false,null,true)\n// false\n</code></pre>\n<p>:::info\nThe function <code>all()</code> replaced the previous function <code>and()</code>. The previous function is deprecated and\nshould not be used anymore.\n:::</p>\n'
  },
  {
    'name': 'any',
    'type': 'function',
    'params': [
      {
        'name': 'list'
      }
    ],
    'info': '<p>Returns <code>true</code> if any element of the given list is <code>true</code>. Otherwise, returns <code>false</code>.</p>\n<p>If the given list is empty, it returns <code>false</code>.</p>\n<p><strong>Function signature</strong></p>\n<pre><code class="language-qlexpression">any(list: list&lt;boolean&gt;): boolean\n</code></pre>\n<p>The parameter <code>list</code> can be passed as a list or as a sequence of elements.</p>\n<p><strong>Examples</strong></p>\n<pre><code class="language-qlexpression">any([false,true])\n// true\n\nany(false,null,true)\n// true\n</code></pre>\n<p>:::info\nThe function <code>any()</code> replaced the previous function <code>or()</code>. The previous function is deprecated and\nshould not be used anymore.\n:::</p>\n'
  },
  {
    'name': 'sublist',
    'type': 'function',
    'params': [
      {
        'name': 'list'
      },
      {
        'name': 'start position'
      }
    ],
    'info': '<p>Returns a partial list of the given value starting at <code>start position</code>.</p>\n<p><strong>Function signature</strong></p>\n<pre><code class="language-qlexpression">sublist(list: list, start position: number): list\n</code></pre>\n<p>The <code>start position</code> starts at the index <code>1</code>. The last position is <code>-1</code>.</p>\n<p><strong>Examples</strong></p>\n<pre><code class="language-qlexpression">sublist([1,2,3], 2)\n// [2,3]\n</code></pre>\n'
  },
  {
    'name': 'sublist',
    'type': 'function',
    'params': [
      {
        'name': 'list'
      },
      {
        'name': 'start position'
      },
      {
        'name': 'length'
      }
    ],
    'info': '<p>Returns a partial list of the given value starting at <code>start position</code>.</p>\n<p><strong>Function signature</strong></p>\n<pre><code class="language-qlexpression">sublist(list: list, start position: number, length: number): list\n</code></pre>\n<p>The <code>start position</code> starts at the index <code>1</code>. The last position is <code>-1</code>.</p>\n<p><strong>Examples</strong></p>\n<pre><code class="language-qlexpression">sublist([1,2,3], 1, 2)\n// [1,2]\n</code></pre>\n'
  },
  {
    'name': 'append',
    'type': 'function',
    'params': [
      {
        'name': 'list'
      },
      {
        'name': 'items'
      }
    ],
    'info': '<p>Returns the given list with all <code>items</code> appended.</p>\n<p><strong>Function signature</strong></p>\n<pre><code class="language-qlexpression">append(list: list, items: Any): list\n</code></pre>\n<p>The parameter <code>items</code> can be a single element or a sequence of elements.</p>\n<p><strong>Examples</strong></p>\n<pre><code class="language-qlexpression">append([1], 2, 3)\n// [1,2,3]\n</code></pre>\n'
  },
  {
    'name': 'concatenate',
    'type': 'function',
    'params': [
      {
        'name': 'lists'
      }
    ],
    'info': '<p>Returns a list that includes all elements of the given lists.</p>\n<p><strong>Function signature</strong></p>\n<pre><code class="language-qlexpression">concatenate(lists: list): list\n</code></pre>\n<p>The parameter <code>lists</code> is a sequence of lists.</p>\n<p><strong>Examples</strong></p>\n<pre><code class="language-qlexpression">concatenate([1,2],[3])\n// [1,2,3]\n\nconcatenate([1],[2],[3])\n// [1,2,3]\n</code></pre>\n'
  },
  {
    'name': 'insertBefore',
    'type': 'function',
    'params': [
      {
        'name': 'list'
      },
      {
        'name': 'position'
      },
      {
        'name': 'newItem'
      }
    ],
    'info': '<p>Returns the given list with <code>newItem</code> inserted at <code>position</code>.</p>\n<p><strong>Function signature</strong></p>\n<pre><code class="language-qlexpression">insertBefore(list: list, position: number, newItem: Any): list\n</code></pre>\n<p>The <code>position</code> starts at the index <code>1</code>. The last position is <code>-1</code>.</p>\n<p><strong>Examples</strong></p>\n<pre><code class="language-qlexpression">insertBefore([1,3],1,2)\n// [2,1,3]\n</code></pre>\n'
  },
  {
    'name': 'remove',
    'type': 'function',
    'params': [
      {
        'name': 'list'
      },
      {
        'name': 'position'
      }
    ],
    'info': '<p>Returns the given list without the element at <code>position</code>.</p>\n<p><strong>Function signature</strong></p>\n<pre><code class="language-qlexpression">remove(list: list, position: number): list\n</code></pre>\n<p>The <code>position</code> starts at the index <code>1</code>. The last position is <code>-1</code>.</p>\n<p><strong>Examples</strong></p>\n<pre><code class="language-qlexpression">remove([1,2,3], 2)\n// [1,3]\n</code></pre>\n'
  },
  {
    'name': 'reverse',
    'type': 'function',
    'params': [
      {
        'name': 'list'
      }
    ],
    'info': '<p>Returns the given list in revered order.</p>\n<p><strong>Function signature</strong></p>\n<pre><code class="language-qlexpression">reverse(list: list): list\n</code></pre>\n<p><strong>Examples</strong></p>\n<pre><code class="language-qlexpression">reverse([1,2,3])\n// [3,2,1]\n</code></pre>\n'
  },
  {
    'name': 'indexOf',
    'type': 'function',
    'params': [
      {
        'name': 'list'
      },
      {
        'name': 'match'
      }
    ],
    'info': '<p>Returns an ascending list of positions containing <code>match</code>.</p>\n<p><strong>Function signature</strong></p>\n<pre><code class="language-qlexpression">indexOf(list: list, match: Any): list&lt;number&gt;\n</code></pre>\n<p><strong>Examples</strong></p>\n<pre><code class="language-qlexpression">indexOf([1,2,3,2],2)\n// [2,4]\n</code></pre>\n'
  },
  {
    'name': 'union',
    'type': 'function',
    'params': [
      {
        'name': 'list'
      }
    ],
    'info': '<p>Returns a list that includes all elements of the given lists without duplicates.</p>\n<p><strong>Function signature</strong></p>\n<pre><code class="language-qlexpression">union(list: list): list\n</code></pre>\n<p>The parameter <code>list</code> is a sequence of lists.</p>\n<p><strong>Examples</strong></p>\n<pre><code class="language-qlexpression">union([1,2],[2,3])\n// [1,2,3]\n</code></pre>\n'
  },
  {
    'name': 'distinctValues',
    'type': 'function',
    'params': [
      {
        'name': 'list'
      }
    ],
    'info': '<p>Returns the given list without duplicates.</p>\n<p><strong>Function signature</strong></p>\n<pre><code class="language-qlexpression">distinctValues(list: list): list\n</code></pre>\n<p><strong>Examples</strong></p>\n<pre><code class="language-qlexpression">distinctValues([1,2,3,2,1])\n// [1,2,3]\n</code></pre>\n'
  },
  {
    'name': 'flatten',
    'type': 'function',
    'params': [
      {
        'name': 'list'
      }
    ],
    'info': '<p>Returns a list that includes all elements of the given list without nested lists.</p>\n<p><strong>Function signature</strong></p>\n<pre><code class="language-qlexpression">flatten(list: list): list\n</code></pre>\n<p><strong>Examples</strong></p>\n<pre><code class="language-qlexpression">flatten([[1,2],[[3]], 4])\n// [1,2,3,4]\n</code></pre>\n'
  },
  {
    'name': 'sort',
    'type': 'function',
    'params': [
      {
        'name': 'list'
      },
      {
        'name': 'precedes'
      }
    ],
    'info': '<p>Returns the given list sorted by the <code>precedes</code> function.</p>\n<p><strong>Function signature</strong></p>\n<pre><code class="language-qlexpression">sort(list: list, precedes: function&lt;(Any, Any) -&gt; boolean&gt;): list\n</code></pre>\n<p><strong>Examples</strong></p>\n<pre><code class="language-qlexpression">sort(list: [3,1,4,5,2], precedes: function(x,y) x &lt; y)\n// [1,2,3,4,5]\n</code></pre>\n'
  },
  {
    'name': 'stringJoin',
    'type': 'function',
    'params': [
      {
        'name': 'list'
      }
    ],
    'info': '<p>Joins a list of strings into a single string. This is similar to\nJava&#39;s <a href="https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/util/stream/Collectors.html#joining(java.lang.CharSequence,java.lang.CharSequence,java.lang.CharSequence)">joining</a>\nfunction.</p>\n<p>If an item of the list is <code>null</code>, the item is ignored for the result string. If an item is\nneither a string nor <code>null</code>, the function returns <code>null</code> instead of a string.</p>\n<p><strong>Function signature</strong></p>\n<pre><code class="language-qlexpression">stringJoin(list: list&lt;string&gt;): string\n</code></pre>\n<p><strong>Examples</strong></p>\n<pre><code class="language-qlexpression">stringJoin([&quot;a&quot;,&quot;b&quot;,&quot;c&quot;])\n// &quot;abc&quot;\n\nstringJoin([&quot;a&quot;,null,&quot;c&quot;])\n// &quot;ac&quot;\n\nstringJoin([])\n// &quot;&quot;\n</code></pre>\n'
  },
  {
    'name': 'stringJoin',
    'type': 'function',
    'params': [
      {
        'name': 'list'
      },
      {
        'name': 'delimiter'
      }
    ],
    'info': '<p>Joins a list of strings into a single string. This is similar to\nJava&#39;s <a href="https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/util/stream/Collectors.html#joining(java.lang.CharSequence,java.lang.CharSequence,java.lang.CharSequence)">joining</a>\nfunction.</p>\n<p>If an item of the list is <code>null</code>, the item is ignored for the result string. If an item is\nneither a string nor <code>null</code>, the function returns <code>null</code> instead of a string.</p>\n<p>The resulting string contains a <code>delimiter</code> between each element.</p>\n<p><strong>Function signature</strong></p>\n<pre><code class="language-qlexpression">stringJoin(list: list&lt;string&gt;, delimiter: string): string\n</code></pre>\n<p><strong>Examples</strong></p>\n<pre><code class="language-qlexpression">stringJoin([&quot;a&quot;], &quot;X&quot;)\n// &quot;a&quot;\n\nstringJoin([&quot;a&quot;,&quot;b&quot;,&quot;c&quot;], &quot;, &quot;)\n// &quot;a, b, c&quot;\n</code></pre>\n'
  },
  {
    'name': 'decimal',
    'type': 'function',
    'params': [
      {
        'name': 'n'
      },
      {
        'name': 'scale'
      }
    ],
    'info': '<p>Rounds the given value at the given scale.</p>\n<p><strong>Function signature</strong></p>\n<pre><code class="language-qlexpression">decimal(n: number, scale: number): number\n</code></pre>\n<p><strong>Examples</strong></p>\n<pre><code class="language-qlexpression">decimal(1/3, 2)\n// .33\n\ndecimal(1.5, 0)\n// 2\n</code></pre>\n'
  },
  {
    'name': 'floor',
    'type': 'function',
    'params': [
      {
        'name': 'n'
      }
    ],
    'info': '<p>Rounds the given value with rounding mode flooring.</p>\n<p><strong>Function signature</strong></p>\n<pre><code class="language-qlexpression">floor(n: number): number\n</code></pre>\n<p><strong>Examples</strong></p>\n<pre><code class="language-qlexpression">floor(1.5)\n// 1\n\nfloor(-1.5)\n// -2\n</code></pre>\n'
  },
  {
    'name': 'floor',
    'type': 'function',
    'params': [
      {
        'name': 'n'
      },
      {
        'name': 'scale'
      }
    ],
    'info': '<p>Rounds the given value with rounding mode flooring at the given scale.</p>\n<p><strong>Function signature</strong></p>\n<pre><code class="language-qlexpression">floor(n: number, scale: number): number\n</code></pre>\n<p><strong>Examples</strong></p>\n<pre><code class="language-qlexpression">floor(-1.56, 1)\n// -1.6\n</code></pre>\n'
  },
  {
    'name': 'ceiling',
    'type': 'function',
    'params': [
      {
        'name': 'n'
      }
    ],
    'info': '<p>Rounds the given value with rounding mode ceiling.</p>\n<p><strong>Function signature</strong></p>\n<pre><code class="language-qlexpression">ceiling(n: number): number\n</code></pre>\n<p><strong>Examples</strong></p>\n<pre><code class="language-qlexpression">ceiling(1.5)\n// 2\n\nceiling(-1.5)\n// -1\n</code></pre>\n'
  },
  {
    'name': 'ceiling',
    'type': 'function',
    'params': [
      {
        'name': 'n'
      },
      {
        'name': 'scale'
      }
    ],
    'info': '<p>Rounds the given value with rounding mode ceiling at the given scale.</p>\n<p><strong>Function signature</strong></p>\n<pre><code class="language-qlexpression">ceiling(n: number, scale: number): number\n</code></pre>\n<p><strong>Examples</strong></p>\n<pre><code class="language-qlexpression">ceiling(-1.56, 1)\n// -1.5\n</code></pre>\n'
  },
  {
    'name': 'roundUp',
    'type': 'function',
    'params': [
      {
        'name': 'n'
      },
      {
        'name': 'scale'
      }
    ],
    'info': '<p>Rounds the given value with the rounding mode round-up at the given scale.</p>\n<p><strong>Function signature</strong></p>\n<pre><code class="language-qlexpression">roundUp(n: number, scale: number): number\n</code></pre>\n<p><strong>Examples</strong></p>\n<pre><code class="language-qlexpression">roundUp(5.5)\n// 6\n\nroundUp(-5.5)\n// -6\n\nroundUp(1.121, 2)\n// 1.13\n\nroundUp(-1.126, 2)\n// -1.13\n</code></pre>\n'
  },
  {
    'name': 'roundDown',
    'type': 'function',
    'params': [
      {
        'name': 'n'
      },
      {
        'name': 'scale'
      }
    ],
    'info': '<p>Rounds the given value with the rounding mode round-down at the given scale.</p>\n<p><strong>Function signature</strong></p>\n<pre><code class="language-qlexpression">roundDown(n: number, scale: number): number\n</code></pre>\n<p><strong>Examples</strong></p>\n<pre><code class="language-qlexpression">roundDown(5.5, 0)\n// 5\n\nroundDown(-5.5, 0)\n// -5\n\nroundDown(1.121, 2)\n// 1.12\n\nroundDown(-1.126, 2)\n// -1.12\n</code></pre>\n'
  },
  {
    'name': 'roundHalfUp',
    'type': 'function',
    'params': [
      {
        'name': 'n'
      },
      {
        'name': 'scale'
      }
    ],
    'info': '<p>Rounds the given value with the rounding mode round-half-up at the given scale.</p>\n<p><strong>Function signature</strong></p>\n<pre><code class="language-qlexpression">roundHalfUp(n: number, scale: number): number\n</code></pre>\n<p><strong>Examples</strong></p>\n<pre><code class="language-qlexpression">roundHalfUp(5.5, 0)\n// 6\n\nroundHalfUp(-5.5, 0)\n// -6\n\nroundHalfUp(1.121, 2)\n// 1.12\n\nroundHalfUp(-1.126, 2)\n// -1.13\n</code></pre>\n'
  },
  {
    'name': 'roundHalfDown',
    'type': 'function',
    'params': [
      {
        'name': 'n'
      },
      {
        'name': 'scale'
      }
    ],
    'info': '<p>Rounds the given value with the rounding mode round-half-down at the given scale.</p>\n<p><strong>Function signature</strong></p>\n<pre><code class="language-qlexpression">roundHalfDown(n: number, scale: number): number\n</code></pre>\n<p><strong>Examples</strong></p>\n<pre><code class="language-qlexpression">roundHalfDown(5.5, 0)\n// 5\n\nroundHalfDown(-5.5, 0)\n// -5\n\nroundHalfDown(1.121, 2)\n// 1.12\n\nroundHalfDown(-1.126, 2)\n// -1.13\n</code></pre>\n'
  },
  {
    'name': 'abs',
    'type': 'function',
    'params': [
      {
        'name': 'number'
      }
    ],
    'info': '<p>Returns the absolute value of the given numeric value.</p>\n<p><strong>Function signature</strong></p>\n<pre><code class="language-qlexpression">abs(number: number): number\n</code></pre>\n<p><strong>Examples</strong></p>\n<pre><code class="language-qlexpression">abs(10)\n// 10\n\nabs(-10)\n// 10\n</code></pre>\n'
  },
  {
    'name': 'modulo',
    'type': 'function',
    'params': [
      {
        'name': 'dividend'
      },
      {
        'name': 'divisor'
      }
    ],
    'info': '<p>Returns the remainder of the division of dividend by divisor.</p>\n<p><strong>Function signature</strong></p>\n<pre><code class="language-qlexpression">modulo(dividend: number, divisor: number): number\n</code></pre>\n<p><strong>Examples</strong></p>\n<pre><code class="language-qlexpression">modulo(12, 5)\n// 2\n</code></pre>\n'
  },
  {
    'name': 'sqrt',
    'type': 'function',
    'params': [
      {
        'name': 'number'
      }
    ],
    'info': '<p>Returns the square root of the given value.</p>\n<p><strong>Function signature</strong></p>\n<pre><code class="language-qlexpression">sqrt(number: number): number\n</code></pre>\n<p><strong>Examples</strong></p>\n<pre><code class="language-qlexpression">sqrt(16)\n// 4\n</code></pre>\n'
  },
  {
    'name': 'log',
    'type': 'function',
    'params': [
      {
        'name': 'number'
      }
    ],
    'info': '<p>Returns the natural logarithm (base e) of the given value.</p>\n<p><strong>Function signature</strong></p>\n<pre><code class="language-qlexpression">log(number: number): number\n</code></pre>\n<p><strong>Examples</strong></p>\n<pre><code class="language-qlexpression">log(10)\n// 2.302585092994046\n</code></pre>\n'
  },
  {
    'name': 'exp',
    'type': 'function',
    'params': [
      {
        'name': 'number'
      }
    ],
    'info': '<p>Returns the Euler’s number e raised to the power of the given number .</p>\n<p><strong>Function signature</strong></p>\n<pre><code class="language-qlexpression">exp(number: number): number\n</code></pre>\n<p><strong>Examples</strong></p>\n<pre><code class="language-qlexpression">exp(5)\n// 148.4131591025766\n</code></pre>\n'
  },
  {
    'name': 'odd',
    'type': 'function',
    'params': [
      {
        'name': 'number'
      }
    ],
    'info': '<p>Returns <code>true</code> if the given value is odd. Otherwise, returns <code>false</code>.</p>\n<p><strong>Function signature</strong></p>\n<pre><code class="language-qlexpression">odd(number: number): boolean\n</code></pre>\n<p><strong>Examples</strong></p>\n<pre><code class="language-qlexpression">odd(5)\n// true\n\nodd(2)\n// false\n</code></pre>\n'
  },
  {
    'name': 'even',
    'type': 'function',
    'params': [
      {
        'name': 'number'
      }
    ],
    'info': '<p>Returns <code>true</code> if the given is even. Otherwise, returns <code>false</code>.</p>\n<p><strong>Function signature</strong></p>\n<pre><code class="language-qlexpression">even(number: number): boolean\n</code></pre>\n<p><strong>Examples</strong></p>\n<pre><code class="language-qlexpression">even(5)\n// false\n\neven(2)\n// true\n</code></pre>\n'
  },
  {
    'name': 'before',
    'type': 'function',
    'params': [
      {
        'name': 'point1'
      },
      {
        'name': 'point2'
      }
    ],
    'info': '<p><strong>Function signature</strong></p>\n<pre><code class="language-qlexpression">before(point1: Any, point2: Any): boolean\n</code></pre>\n<p><strong>Examples</strong></p>\n<pre><code class="language-qlexpression">before(1, 10)\n// true\n\nbefore(10, 1)\n// false\n</code></pre>\n'
  },
  {
    'name': 'before',
    'type': 'function',
    'params': [
      {
        'name': 'range'
      },
      {
        'name': 'point'
      }
    ],
    'info': '<p><strong>Function signature</strong></p>\n<pre><code class="language-qlexpression">before(range: range, point: Any): boolean\n</code></pre>\n<p><strong>Examples</strong></p>\n<pre><code class="language-qlexpression">before([1..5], 10)\n// true\n</code></pre>\n'
  },
  {
    'name': 'before',
    'type': 'function',
    'params': [
      {
        'name': 'point'
      },
      {
        'name': 'range'
      }
    ],
    'info': '<p><strong>Function signature</strong></p>\n<pre><code class="language-qlexpression">before(point: Any, range: range): boolean\n</code></pre>\n<p><strong>Examples</strong></p>\n<pre><code class="language-qlexpression">before(1, [2..5])\n// true\n</code></pre>\n'
  },
  {
    'name': 'before',
    'type': 'function',
    'params': [
      {
        'name': 'range1'
      },
      {
        'name': 'range2'
      }
    ],
    'info': '<p><strong>Function signature</strong></p>\n<pre><code class="language-qlexpression">before(range1: range, range2: range): boolean\n</code></pre>\n<p><strong>Examples</strong></p>\n<pre><code class="language-qlexpression">before([1..5], [6..10])\n// true\n\nbefore([1..5),[5..10])\n// true\n</code></pre>\n'
  },
  {
    'name': 'after',
    'type': 'function',
    'params': [
      {
        'name': 'point1'
      },
      {
        'name': 'point2'
      }
    ],
    'info': '<p><strong>Function signature</strong></p>\n<pre><code class="language-qlexpression">after(point1: Any, point2: Any): boolean\n</code></pre>\n<p><strong>Examples</strong></p>\n<pre><code class="language-qlexpression">after(10, 1)\n// true\n\nafter(1, 10)\n// false\n</code></pre>\n'
  },
  {
    'name': 'after',
    'type': 'function',
    'params': [
      {
        'name': 'range'
      },
      {
        'name': 'point'
      }
    ],
    'info': '<p><strong>Function signature</strong></p>\n<pre><code class="language-qlexpression">after(range: range, point: Any): boolean\n</code></pre>\n<p><strong>Examples</strong></p>\n<pre><code class="language-qlexpression">after([1..5], 10)\n// false\n</code></pre>\n'
  },
  {
    'name': 'after',
    'type': 'function',
    'params': [
      {
        'name': 'point'
      },
      {
        'name': 'range'
      }
    ],
    'info': '<p><strong>Function signature</strong></p>\n<pre><code class="language-qlexpression">after(point: Any, range: range): boolean\n</code></pre>\n<p><strong>Examples</strong></p>\n<pre><code class="language-qlexpression">after(12, [2..5])\n// true\n</code></pre>\n'
  },
  {
    'name': 'after',
    'type': 'function',
    'params': [
      {
        'name': 'range1'
      },
      {
        'name': 'range2'
      }
    ],
    'info': '<p><strong>Function signature</strong></p>\n<pre><code class="language-qlexpression">after(range1: range, range2: range): boolean\n</code></pre>\n<p><strong>Examples</strong></p>\n<pre><code class="language-qlexpression">after([6..10], [1..5])\n// true\n\nafter([5..10], [1..5))\n// true\n</code></pre>\n'
  },
  {
    'name': 'meets',
    'type': 'function',
    'params': [
      {
        'name': 'range1'
      },
      {
        'name': 'range2'
      }
    ],
    'info': '<p><strong>Function signature</strong></p>\n<pre><code class="language-qlexpression">meets(range1: range, range2: range): boolean\n</code></pre>\n<p><strong>Examples</strong></p>\n<pre><code class="language-qlexpression">meets([1..5], [5..10])\n// true\n\nmeets([1..3], [4..6])\n// false\n\nmeets([1..3], [3..5])\n// true\n\nmeets([1..5], (5..8])\n// false\n</code></pre>\n'
  },
  {
    'name': 'metBy',
    'type': 'function',
    'params': [
      {
        'name': 'range1'
      },
      {
        'name': 'range2'
      }
    ],
    'info': '<p><strong>Function signature</strong></p>\n<pre><code class="language-qlexpression">metBy(range1: range, range2: range): boolean\n</code></pre>\n<p><strong>Examples</strong></p>\n<pre><code class="language-qlexpression">metBy([5..10], [1..5])\n// true\n\nmetBy([3..4], [1..2])\n// false\n\nmetBy([3..5], [1..3])\n// true\n\nmetBy((5..8], [1..5))\n// false\n\nmetBy([5..10], [1..5))\n// false\n</code></pre>\n'
  },
  {
    'name': 'overlaps',
    'type': 'function',
    'params': [
      {
        'name': 'range1'
      },
      {
        'name': 'range2'
      }
    ],
    'info': '<p><strong>Function signature</strong></p>\n<pre><code class="language-qlexpression">overlaps(range1: range, range2: range): boolean\n</code></pre>\n<p><strong>Examples</strong></p>\n<pre><code class="language-qlexpression">overlaps([5..10], [1..6])\n// true\n\noverlaps((3..7], [1..4])\n// true\n\noverlaps([1..3], (3..6])\n// false\n\noverlaps((5..8], [1..5))\n// false\n\noverlaps([4..10], [1..5))\n// true\n</code></pre>\n'
  },
  {
    'name': 'overlapsBefore',
    'type': 'function',
    'params': [
      {
        'name': 'range1'
      },
      {
        'name': 'range2'
      }
    ],
    'info': '<p><strong>Function signature</strong></p>\n<pre><code class="language-qlexpression">overlapsBefore(range1: range, range2: range): boolean\n</code></pre>\n<p><strong>Examples</strong></p>\n<pre><code class="language-qlexpression">overlapsBefore([1..5], [4..10])\n// true\n\noverlapsBefore([3..4], [1..2])\n// false\n\noverlapsBefore([1..3], (3..5])\n// false\n\noverlapsBefore([1..5), (3..8])\n// true\n\noverlapsBefore([1..5), [5..10])\n// false\n</code></pre>\n'
  },
  {
    'name': 'overlapsAfter',
    'type': 'function',
    'params': [
      {
        'name': 'range1'
      },
      {
        'name': 'range2'
      }
    ],
    'info': '<p><strong>Function signature</strong></p>\n<pre><code class="language-qlexpression">overlapsAfter(range1: range, range2: range): boolean\n</code></pre>\n<p><strong>Examples</strong></p>\n<pre><code class="language-qlexpression">overlapsAfter([4..10], [1..5])\n// true\n\noverlapsAfter([3..4], [1..2])\n// false\n\noverlapsAfter([3..5], [1..3))\n// false\n\noverlapsAfter((5..8], [1..5))\n// false\n\noverlapsAfter([4..10], [1..5))\n// true\n</code></pre>\n'
  },
  {
    'name': 'finishes',
    'type': 'function',
    'params': [
      {
        'name': 'point'
      },
      {
        'name': 'range'
      }
    ],
    'info': '<p><strong>Function signature</strong></p>\n<pre><code class="language-qlexpression">finishes(point: Any, range: range): boolean\n</code></pre>\n<p><strong>Examples</strong></p>\n<pre><code class="language-qlexpression">finishes(5, [1..5])\n// true\n\nfinishes(10, [1..7])\n// false\n</code></pre>\n'
  },
  {
    'name': 'finishes',
    'type': 'function',
    'params': [
      {
        'name': 'range1'
      },
      {
        'name': 'range2'
      }
    ],
    'info': '<p><strong>Function signature</strong></p>\n<pre><code class="language-qlexpression">finishes(range1: range, range2: range): boolean\n</code></pre>\n<p><strong>Examples</strong></p>\n<pre><code class="language-qlexpression">finishes([3..5], [1..5])\n// true\n\nfinishes((1..5], [1..5))\n// false\n\nfinishes([5..10], [1..10))\n// false\n</code></pre>\n'
  },
  {
    'name': 'finishedBy',
    'type': 'function',
    'params': [
      {
        'name': 'range'
      },
      {
        'name': 'point'
      }
    ],
    'info': '<p><strong>Function signature</strong></p>\n<pre><code class="language-qlexpression">finishedBy(range: range, point: Any): boolean\n</code></pre>\n<p><strong>Examples</strong></p>\n<pre><code class="language-qlexpression">finishedBy([5..10], 10)\n// true\n\nfinishedBy([3..4], 2)\n// false\n</code></pre>\n'
  },
  {
    'name': 'finishedBy',
    'type': 'function',
    'params': [
      {
        'name': 'range1'
      },
      {
        'name': 'range2'
      }
    ],
    'info': '<p><strong>Function signature</strong></p>\n<pre><code class="language-qlexpression">finishedBy(range1: range, range2: range): boolean\n</code></pre>\n<p><strong>Examples</strong></p>\n<pre><code class="language-qlexpression">finishedBy([1..5], [3..5])\n// true\n\nfinishedBy((5..8], [1..5))\n// false\n\nfinishedBy([5..10], (1..10))\n// false\n</code></pre>\n'
  },
  {
    'name': 'includes',
    'type': 'function',
    'params': [
      {
        'name': 'range'
      },
      {
        'name': 'point'
      }
    ],
    'info': '<p><strong>Function signature</strong></p>\n<pre><code class="language-qlexpression">includes(range: range, point: Any): boolean\n</code></pre>\n<p><strong>Examples</strong></p>\n<pre><code class="language-qlexpression">includes([5..10], 6)\n// true\n\nincludes([3..4], 5)\n// false\n</code></pre>\n'
  },
  {
    'name': 'includes',
    'type': 'function',
    'params': [
      {
        'name': 'range1'
      },
      {
        'name': 'range2'
      }
    ],
    'info': '<p><strong>Function signature</strong></p>\n<pre><code class="language-qlexpression">includes(range1: range, range2: range): boolean\n</code></pre>\n<p><strong>Examples</strong></p>\n<pre><code class="language-qlexpression">includes([1..10], [4..6])\n// true\n\nincludes((5..8], [1..5))\n// false\n\nincludes([1..10], [1..5))\n// true\n</code></pre>\n'
  },
  {
    'name': 'during',
    'type': 'function',
    'params': [
      {
        'name': 'point'
      },
      {
        'name': 'range'
      }
    ],
    'info': '<p><strong>Function signature</strong></p>\n<pre><code class="language-qlexpression">during(point: Any, range: range): boolean\n</code></pre>\n<p><strong>Examples</strong></p>\n<pre><code class="language-qlexpression">during(5, [1..10])\n// true\n\nduring(12, [1..10])\n// false\n\nduring(1, (1..10])\n// false\n</code></pre>\n'
  },
  {
    'name': 'during',
    'type': 'function',
    'params': [
      {
        'name': 'range1'
      },
      {
        'name': 'range2'
      }
    ],
    'info': '<p><strong>Function signature</strong></p>\n<pre><code class="language-qlexpression">during(range1: range, range2: range): boolean\n</code></pre>\n<p><strong>Examples</strong></p>\n<pre><code class="language-qlexpression">during([4..6], [1..10))\n// true\n\nduring((1..5], (1..10])\n// true\n</code></pre>\n'
  },
  {
    'name': 'starts',
    'type': 'function',
    'params': [
      {
        'name': 'point'
      },
      {
        'name': 'range'
      }
    ],
    'info': '<p><strong>Function signature</strong></p>\n<pre><code class="language-qlexpression">starts(point: Any, range: range): boolean\n</code></pre>\n<p><strong>Examples</strong></p>\n<pre><code class="language-qlexpression">starts(1, [1..5])\n// true\n\nstarts(1, (1..8])\n// false\n</code></pre>\n'
  },
  {
    'name': 'starts',
    'type': 'function',
    'params': [
      {
        'name': 'range1'
      },
      {
        'name': 'range2'
      }
    ],
    'info': '<p><strong>Function signature</strong></p>\n<pre><code class="language-qlexpression">starts(range1: range, range2: range): boolean\n</code></pre>\n<p><strong>Examples</strong></p>\n<pre><code class="language-qlexpression">starts((1..5], [1..5])\n// false\n\nstarts([1..10], [1..5])\n// false\n\nstarts((1..5), (1..10))\n// true\n</code></pre>\n'
  },
  {
    'name': 'startedBy',
    'type': 'function',
    'params': [
      {
        'name': 'range'
      },
      {
        'name': 'point'
      }
    ],
    'info': '<p><strong>Function signature</strong></p>\n<pre><code class="language-qlexpression">startedBy(range: range, point: Any): boolean\n</code></pre>\n<p><strong>Examples</strong></p>\n<pre><code class="language-qlexpression">startedBy([1..10], 1)\n// true\n\nstartedBy((1..10], 1)\n// false\n</code></pre>\n'
  },
  {
    'name': 'startedBy',
    'type': 'function',
    'params': [
      {
        'name': 'range1'
      },
      {
        'name': 'range2'
      }
    ],
    'info': '<p><strong>Function signature</strong></p>\n<pre><code class="language-qlexpression">startedBy(range1: range, range2: range): boolean\n</code></pre>\n<p><strong>Examples</strong></p>\n<pre><code class="language-qlexpression">startedBy([1..10], [1..5])\n// true\n\nstartedBy((1..10], [1..5))\n// false\n\nstartedBy([1..10], [1..10))\n// true\n</code></pre>\n'
  },
  {
    'name': 'coincides',
    'type': 'function',
    'params': [
      {
        'name': 'point1'
      },
      {
        'name': 'point2'
      }
    ],
    'info': '<p><strong>Function signature</strong></p>\n<pre><code class="language-qlexpression">coincides(point1: Any, point2: Any): boolean\n</code></pre>\n<p><strong>Examples</strong></p>\n<pre><code class="language-qlexpression">coincides(5, 5)\n// true\n\ncoincides(3, 4)\n// false\n</code></pre>\n'
  },
  {
    'name': 'coincides',
    'type': 'function',
    'params': [
      {
        'name': 'range1'
      },
      {
        'name': 'range2'
      }
    ],
    'info': '<p><strong>Function signature</strong></p>\n<pre><code class="language-qlexpression">coincides(range1: range, range2: range): boolean\n</code></pre>\n<p><strong>Examples</strong></p>\n<pre><code class="language-qlexpression">coincides([1..5], [1..5])\n// true\n\ncoincides((1..5], [1..5))\n// false\n\ncoincides([1..5], [2..6])\n// false\n</code></pre>\n'
  },
  {
    'name': 'substring',
    'type': 'function',
    'params': [
      {
        'name': 'string'
      },
      {
        'name': 'start position'
      }
    ],
    'info': '<p>Returns a substring of the given value starting at <code>start position</code>.</p>\n<p><strong>Function signature</strong></p>\n<pre><code class="language-qlexpression">substring(string: string, start position: number): string\n</code></pre>\n<p>The <code>start position</code> starts at the index <code>1</code>. The last position is <code>-1</code>.</p>\n<p><strong>Examples</strong></p>\n<pre><code class="language-qlexpression">substring(&quot;foobar&quot;, 3)\n// &quot;obar&quot;\n\nsubstring(&quot;foobar&quot;, -2)\n// &quot;ar&quot;\n</code></pre>\n'
  },
  {
    'name': 'substring',
    'type': 'function',
    'params': [
      {
        'name': 'string'
      },
      {
        'name': 'start position'
      },
      {
        'name': 'length'
      }
    ],
    'info': '<p>Returns a substring of the given value, starting at <code>start position</code> with the given <code>length</code>. If <code>length</code> is greater than\nthe remaining characters of the value, it returns all characters from <code>start position</code> until the end.</p>\n<p><strong>Function signature</strong></p>\n<pre><code class="language-qlexpression">substring(string: string, start position: number, length: number): string\n</code></pre>\n<p>The <code>start position</code> starts at the index <code>1</code>. The last position is <code>-1</code>.</p>\n<p><strong>Examples</strong></p>\n<pre><code class="language-qlexpression">substring(&quot;foobar&quot;, 3, 3)\n// &quot;oba&quot;\n\nsubstring(&quot;foobar&quot;, -3, 2)\n// &quot;ba&quot;\n\nsubstring(&quot;foobar&quot;, 3, 10)\n// &quot;obar&quot;\n</code></pre>\n'
  },
  {
    'name': 'stringLength',
    'type': 'function',
    'params': [
      {
        'name': 'string'
      }
    ],
    'info': '<p>Returns the number of characters in the given value.</p>\n<p><strong>Function signature</strong></p>\n<pre><code class="language-qlexpression">stringLength(string: string): number\n</code></pre>\n<p><strong>Examples</strong></p>\n<pre><code class="language-qlexpression">stringLength(&quot;foo&quot;)\n// 3\n</code></pre>\n'
  },
  {
    'name': 'upperCase',
    'type': 'function',
    'params': [
      {
        'name': 'string'
      }
    ],
    'info': '<p>Returns the given value with all characters are uppercase.</p>\n<p><strong>Function signature</strong></p>\n<pre><code class="language-qlexpression">upperCase(string: string): string\n</code></pre>\n<p><strong>Examples</strong></p>\n<pre><code class="language-qlexpression">upperCase(&quot;aBc4&quot;)\n// &quot;ABC4&quot;\n</code></pre>\n'
  },
  {
    'name': 'lowerCase',
    'type': 'function',
    'params': [
      {
        'name': 'string'
      }
    ],
    'info': '<p>Returns the given value with all characters are lowercase.</p>\n<p><strong>Function signature</strong></p>\n<pre><code class="language-qlexpression">lowerCase(string: string): string\n</code></pre>\n<p><strong>Examples</strong></p>\n<pre><code class="language-qlexpression">lowerCase(&quot;aBc4&quot;)\n// &quot;abc4&quot;\n</code></pre>\n'
  },
  {
    'name': 'substringBefore',
    'type': 'function',
    'params': [
      {
        'name': 'string'
      },
      {
        'name': 'match'
      }
    ],
    'info': '<p>Returns a substring of the given value that contains all characters before <code>match</code>.</p>\n<p><strong>Function signature</strong></p>\n<pre><code class="language-qlexpression">substringBefore(string: string, match: string): string\n</code></pre>\n<p><strong>Examples</strong></p>\n<pre><code class="language-qlexpression">substringBefore(&quot;foobar&quot;, &quot;bar&quot;)\n// &quot;foo&quot;\n</code></pre>\n'
  },
  {
    'name': 'substringAfter',
    'type': 'function',
    'params': [
      {
        'name': 'string'
      },
      {
        'name': 'match'
      }
    ],
    'info': '<p>Returns a substring of the given value that contains all characters after <code>match</code>.</p>\n<p><strong>Function signature</strong></p>\n<pre><code class="language-qlexpression">substringAfter(string: string, match: string): string\n</code></pre>\n<p><strong>Examples</strong></p>\n<pre><code class="language-qlexpression">substringAfter(&quot;foobar&quot;, &quot;ob&quot;)\n// &quot;ar&quot;\n</code></pre>\n'
  },
  {
    'name': 'contains',
    'type': 'function',
    'params': [
      {
        'name': 'string'
      },
      {
        'name': 'match'
      }
    ],
    'info': '<p>Returns <code>true</code> if the given value contains the substring <code>match</code>. Otherwise, returns <code>false</code>.</p>\n<p><strong>Function signature</strong></p>\n<pre><code class="language-qlexpression">contains(string: string, match: string): boolean\n</code></pre>\n<p><strong>Examples</strong></p>\n<pre><code class="language-qlexpression">contains(&quot;foobar&quot;, &quot;of&quot;)\n// false\n</code></pre>\n'
  },
  {
    'name': 'startsWith',
    'type': 'function',
    'params': [
      {
        'name': 'string'
      },
      {
        'name': 'match'
      }
    ],
    'info': '<p>Returns <code>true</code> if the given value starts with the substring <code>match</code>. Otherwise, returns <code>false</code>.</p>\n<p><strong>Function signature</strong></p>\n<pre><code class="language-qlexpression">startsWith(string: string, match: string): boolean\n</code></pre>\n<p><strong>Examples</strong></p>\n<pre><code class="language-qlexpression">startsWith(&quot;foobar&quot;, &quot;fo&quot;)\n// true\n</code></pre>\n'
  },
  {
    'name': 'endsWith',
    'type': 'function',
    'params': [
      {
        'name': 'string'
      },
      {
        'name': 'match'
      }
    ],
    'info': '<p>Returns <code>true</code> if the given value ends with the substring <code>match</code>. Otherwise, returns <code>false</code>.</p>\n<p><strong>Function signature</strong></p>\n<pre><code class="language-qlexpression">endsWith(string: string, match: string): boolean\n</code></pre>\n<p><strong>Examples</strong></p>\n<pre><code class="language-qlexpression">endsWith(&quot;foobar&quot;, &quot;r&quot;)\n// true\n</code></pre>\n'
  },
  {
    'name': 'matches',
    'type': 'function',
    'params': [
      {
        'name': 'input'
      },
      {
        'name': 'pattern'
      }
    ],
    'info': '<p>Returns <code>true</code> if the given value matches the <code>pattern</code>. Otherwise, returns <code>false</code>.</p>\n<p><strong>Function signature</strong></p>\n<pre><code class="language-qlexpression">matches(input: string, pattern: string): boolean\n</code></pre>\n<p>The <code>pattern</code> is a string that contains a regular expression.</p>\n<p><strong>Examples</strong></p>\n<pre><code class="language-qlexpression">matches(&quot;foobar&quot;, &quot;^fo*bar&quot;)\n// true\n</code></pre>\n'
  },
  {
    'name': 'matches',
    'type': 'function',
    'params': [
      {
        'name': 'input'
      },
      {
        'name': 'pattern'
      },
      {
        'name': 'flags'
      }
    ],
    'info': '<p>Returns <code>true</code> if the given value matches the <code>pattern</code>. Otherwise, returns <code>false</code>.</p>\n<p><strong>Function signature</strong></p>\n<pre><code class="language-qlexpression">matches(input: string, pattern: string, flags: string): boolean\n</code></pre>\n<p>The <code>pattern</code> is a string that contains a regular expression.</p>\n<p>The <code>flags</code> can contain one or more of the following characters:</p>\n<ul>\n<li><code>s</code> (dot-all)</li>\n<li><code>m</code> (multi-line)</li>\n<li><code>i</code> (case insensitive)</li>\n<li><code>x</code> (comments)</li>\n</ul>\n<p><strong>Examples</strong></p>\n<pre><code class="language-qlexpression">matches(&quot;FooBar&quot;, &quot;foo&quot;, &quot;i&quot;)\n// true\n</code></pre>\n'
  },
  {
    'name': 'replace',
    'type': 'function',
    'params': [
      {
        'name': 'input'
      },
      {
        'name': 'pattern'
      },
      {
        'name': 'replacement'
      }
    ],
    'info': '<p>Returns the resulting string after replacing all occurrences of <code>pattern</code> with <code>replacement</code>.</p>\n<p><strong>Function signature</strong></p>\n<pre><code class="language-qlexpression">replace(input: string, pattern: string, replacement: string): string\n</code></pre>\n<p>The <code>pattern</code> is a string that contains a regular expression.</p>\n<p>The <code>replacement</code> can access the match groups by using <code>$</code> and the number of the group, for example,\n<code>$1</code> to access the first group.</p>\n<p><strong>Examples</strong></p>\n<pre><code class="language-qlexpression">replace(&quot;abcd&quot;, &quot;(ab)|(a)&quot;, &quot;[1=$1][2=$2]&quot;)\n// &quot;[1=ab][2=]cd&quot;\n\nreplace(&quot;0123456789&quot;, &quot;(\\d{3})(\\d{3})(\\d{4})&quot;, &quot;($1) $2-$3&quot;)\n// &quot;(012) 345-6789&quot;\n</code></pre>\n'
  },
  {
    'name': 'replace',
    'type': 'function',
    'params': [
      {
        'name': 'input'
      },
      {
        'name': 'pattern'
      },
      {
        'name': 'replacement'
      },
      {
        'name': 'flags'
      }
    ],
    'info': '<p>Returns the resulting string after replacing all occurrences of <code>pattern</code> with <code>replacement</code>.</p>\n<p><strong>Function signature</strong></p>\n<pre><code class="language-qlexpression">replace(input: string, pattern: string, replacement: string, flags: string): string\n</code></pre>\n<p>The <code>pattern</code> is a string that contains a regular expression.</p>\n<p>The <code>replacement</code> can access the match groups by using <code>$</code> and the number of the group, for example,\n<code>$1</code> to access the first group.</p>\n<p>The <code>flags</code> can contain one or more of the following characters:</p>\n<ul>\n<li><code>s</code> (dot-all)</li>\n<li><code>m</code> (multi-line)</li>\n<li><code>i</code> (case insensitive)</li>\n<li><code>x</code> (comments)</li>\n</ul>\n<p><strong>Examples</strong></p>\n<pre><code class="language-qlexpression">replace(&quot;How do you feel?&quot;, &quot;Feel&quot;, &quot;FEEL&quot;, &quot;i&quot;)\n// &quot;How do you FEEL?&quot;\n</code></pre>\n'
  },
  {
    'name': 'split',
    'type': 'function',
    'params': [
      {
        'name': 'string'
      },
      {
        'name': 'delimiter'
      }
    ],
    'info': '<p>Splits the given value into a list of substrings, breaking at each occurrence of the <code>delimiter</code> pattern.</p>\n<p><strong>Function signature</strong></p>\n<pre><code class="language-qlexpression">split(string: string, delimiter: string): list&lt;string&gt;\n</code></pre>\n<p>The <code>delimiter</code> is a string that contains a regular expression.</p>\n<p><strong>Examples</strong></p>\n<pre><code class="language-qlexpression">split(&quot;John Doe&quot;, &quot;\\s&quot; )\n// [&quot;John&quot;, &quot;Doe&quot;]\n\nsplit(&quot;a;b;c;;&quot;, &quot;;&quot;)\n// [&quot;a&quot;, &quot;b&quot;, &quot;c&quot;, &quot;&quot;, &quot;&quot;]\n</code></pre>\n'
  },
  {
    'name': 'now',
    'type': 'function',
    'params': [],
    'info': '<p>Returns the current date and time including the timezone.</p>\n<p><strong>Function signature</strong></p>\n<pre><code class="language-qlexpression">now(): date and time\n</code></pre>\n<p><strong>Examples</strong></p>\n<pre><code class="language-qlexpression">now()\n// dateTime(&quot;2020-07-31T14:27:30@Europe/Berlin&quot;)\n</code></pre>\n'
  },
  {
    'name': 'today',
    'type': 'function',
    'params': [],
    'info': '<p>Returns the current date.</p>\n<p><strong>Function signature</strong></p>\n<pre><code class="language-qlexpression">today(): date\n</code></pre>\n<p><strong>Examples</strong></p>\n<pre><code class="language-qlexpression">today()\n// date(&quot;2020-07-31&quot;)\n</code></pre>\n'
  },
  {
    'name': 'dayOfWeek',
    'type': 'function',
    'params': [
      {
        'name': 'date'
      }
    ],
    'info': '<p>Returns the day of the week according to the Gregorian calendar. Note that it always returns the English name of the day.</p>\n<p><strong>Function signature</strong></p>\n<pre><code class="language-qlexpression">dayOfWeek(date: date): string\n</code></pre>\n<pre><code class="language-qlexpression">dayOfWeek(date: date and time): string\n</code></pre>\n<p><strong>Examples</strong></p>\n<pre><code class="language-qlexpression">dayOfWeek(date(&quot;2019-09-17&quot;))\n// &quot;Tuesday&quot;\n\ndayOfWeek(dateTime(&quot;2019-09-17T12:00:00&quot;))\n// &quot;Tuesday&quot;\n</code></pre>\n'
  },
  {
    'name': 'dayOfYear',
    'type': 'function',
    'params': [
      {
        'name': 'date'
      }
    ],
    'info': '<p>Returns the Gregorian number of the day within the year.</p>\n<p><strong>Function signature</strong></p>\n<pre><code class="language-qlexpression">dayOfYear(date: date): number\n</code></pre>\n<pre><code class="language-qlexpression">dayOfYear(date: date and time): number\n</code></pre>\n<p><strong>Examples</strong></p>\n<pre><code class="language-qlexpression">dayOfYear(date(&quot;2019-09-17&quot;))\n// 260\n\ndayOfYear(dateTime(&quot;2019-09-17T12:00:00&quot;))\n// 260\n</code></pre>\n'
  },
  {
    'name': 'weekOfYear',
    'type': 'function',
    'params': [
      {
        'name': 'date'
      }
    ],
    'info': '<p>Returns the Gregorian number of the week within the year, according to ISO 8601.</p>\n<p><strong>Function signature</strong></p>\n<pre><code class="language-qlexpression">weekOfYear(date: date): number\n</code></pre>\n<pre><code class="language-qlexpression">weekOfYear(date: date and time): number\n</code></pre>\n<p><strong>Examples</strong></p>\n<pre><code class="language-qlexpression">weekOfYear(date(&quot;2019-09-17&quot;))\n// 38\n\nweekOfYear(dateTime(&quot;2019-09-17T12:00:00&quot;))\n// 38\n</code></pre>\n'
  },
  {
    'name': 'monthOfYear',
    'type': 'function',
    'params': [
      {
        'name': 'date'
      }
    ],
    'info': '<p>Returns the month of the year according to the Gregorian calendar. Note that it always returns the English name of the month.</p>\n<p><strong>Function signature</strong></p>\n<pre><code class="language-qlexpression">monthOfYear(date: date): string\n</code></pre>\n<pre><code class="language-qlexpression">monthOfYear(date: date and time): string\n</code></pre>\n<p><strong>Examples</strong></p>\n<pre><code class="language-qlexpression">monthOfYear(date(&quot;2019-09-17&quot;))\n// &quot;September&quot;\n\nmonthOfYear(dateTime(&quot;2019-09-17T12:00:00&quot;))\n// &quot;September&quot;\n</code></pre>\n'
  },
  {
    'name': 'abs',
    'type': 'function',
    'params': [
      {
        'name': 'n'
      }
    ],
    'info': '<p>Returns the absolute value of a given duration.</p>\n<p><strong>Function signature</strong></p>\n<pre><code class="language-qlexpression">abs(n: days and time duration): days and time duration\n</code></pre>\n<pre><code class="language-qlexpression">abs(n: years and months duration): years and months duration\n</code></pre>\n<p><strong>Examples</strong></p>\n<pre><code class="language-qlexpression">abs(duration(&quot;-PT5H&quot;))\n// &quot;duration(&quot;PT5H&quot;)&quot;\n\nabs(duration(&quot;PT5H&quot;))\n// &quot;duration(&quot;PT5H&quot;)&quot;\n\nabs(duration(&quot;-P2M&quot;))\n// duration(&quot;P2M&quot;)\n</code></pre>\n'
  }
];

/**
 * List of FEEL kunpeng extensions.
 *
 * @type { Builtin[] }
 */
export const kunpengExtensions = [
  {
    'name': 'isDefined',
    'type': 'function',
    'params': [
      {
        'name': 'value'
      }
    ],
    'info': '<p><em>Kunpeng Extension</em></p>\n<p>Checks if a given value is not <code>null</code>. If the value is <code>null</code> then the function returns <code>false</code>.\nOtherwise, the function returns <code>true</code>.</p>\n<p>The function requires one argument. Calling <code>isDefined()</code> without an argument is invalid.</p>\n<p><strong>Function signature</strong></p>\n<pre><code class="language-qlexpression">isDefined(value: Any): boolean\n</code></pre>\n<p><strong>Examples</strong></p>\n<pre><code class="language-qlexpression">isDefined(1)\n// true\n\nisDefined(null)\n// false\n\nisDefined(x)\n// false - if no variable &quot;x&quot; exists\n\nisDefined(x.y)\n// false - if no variable &quot;x&quot; exists or it doesn&#39;t have a property &quot;y&quot;\n\nisDefined()\n// error - expected one argument\n</code></pre>\n<p>:::caution Breaking change</p>\n<p>This function worked differently in previous versions. It returned <code>true</code> if the value was <code>null</code>.\nSince this version, the function returns <code>false</code> if the value is <code>null</code>.</p>\n<p>:::</p>\n'
  },
  {
    'name': 'getOrElse',
    'type': 'function',
    'params': [
      {
        'name': 'value'
      },
      {
        'name': 'default'
      }
    ],
    'info': '<p><em>Kunpeng Extension</em></p>\n<p>Return the provided value parameter if not <code>null</code>, otherwise return the default parameter</p>\n<p><strong>Function signature</strong></p>\n<pre><code class="language-qlexpression">getOrElse(value: Any, default: Any): Any\n</code></pre>\n<p><strong>Examples</strong></p>\n<pre><code class="language-qlexpression">getOrElse(&quot;this&quot;, &quot;default&quot;)\n// &quot;this&quot;\n\ngetOrElse(null, &quot;default&quot;)\n// &quot;default&quot;\n\ngetOrElse(null, null)\n// null\n</code></pre>\n',
    'engines': {
      'kunpeng': '>=8.3'
    }
  },
  {
    'name': 'assert',
    'type': 'function',
    'params': [
      {
        'name': 'value'
      },
      {
        'name': 'condition'
      }
    ],
    'info': '<p><em>Kunpeng Extension</em></p>\n<p>Verify that the given condition is met. If the condition is <code>true</code>, the function returns the value.\nOtherwise, the evaluation fails with an error.</p>\n<p><strong>Function signature</strong></p>\n<pre><code class="language-qlexpression">assert(value: Any, condition: Any)\n</code></pre>\n<p><strong>Examples</strong></p>\n<pre><code class="language-qlexpression">assert(x, x != null)\n// &quot;value&quot; - if x is &quot;value&quot;\n// error - if x is null or doesn&#39;t exist\n\nassert(x, x &gt;= 0)\n// 4 - if x is 4\n// error - if x is less than zero\n</code></pre>\n',
    'engines': {
      'kunpeng': '>=8.3'
    }
  },
  {
    'name': 'assert',
    'type': 'function',
    'params': [
      {
        'name': 'value'
      },
      {
        'name': 'condition'
      },
      {
        'name': 'cause'
      }
    ],
    'info': '<p><em>Kunpeng Extension</em></p>\n<p>Verify that the given condition is met. If the condition is <code>true</code>, the function returns the value.\nOtherwise, the evaluation fails with an error containing the given message.</p>\n<p><strong>Function signature</strong></p>\n<pre><code class="language-qlexpression">assert(value: Any, condition: Any, cause: String)\n</code></pre>\n<p><strong>Examples</strong></p>\n<pre><code class="language-qlexpression">assert(x, x != null, &quot;&#39;x&#39; should not be null&quot;)\n// &quot;value&quot; - if x is &quot;value&quot;\n// error(&#39;x&#39; should not be null) - if x is null or doesn&#39;t exist\n\nassert(x, x &gt;= 0, &quot;&#39;x&#39; should be positive&quot;)\n// 4 - if x is 4\n// error(&#39;x&#39; should be positive) - if x is less than zero\n</code></pre>\n',
    'engines': {
      'kunpeng': '>=8.3'
    }
  },
  {
    'name': 'getValue',
    'type': 'function',
    'params': [
      {
        'name': 'context'
      },
      {
        'name': 'keys'
      }
    ],
    'info': '<p><em>Kunpeng Extension</em></p>\n<p>Returns the value of the context entry for a context path defined by the given keys.</p>\n<p>If <code>keys</code> contains the keys <code>[k1, k2]</code> then it returns the value at the nested entry <code>k1.k2</code> of the context.</p>\n<p>If <code>keys</code> are empty or the nested entry defined by the keys doesn&#39;t exist in the context, it returns <code>null</code>.</p>\n<p><strong>Function signature</strong></p>\n<pre><code class="language-qlexpression">getValue(context: context, keys: list&lt;string&gt;): Any\n</code></pre>\n<p><strong>Examples</strong></p>\n<pre><code class="language-qlexpression">getValue({x:1, y: {z:0}}, [&quot;y&quot;, &quot;z&quot;])\n// 0\n\ngetValue({x: {y: {z:0}}}, [&quot;x&quot;, &quot;y&quot;])\n// {z:0}\n\ngetValue({a: {b: 3}}, [&quot;b&quot;])\n// null\n</code></pre>\n'
  },
  {
    'name': 'contextPut',
    'type': 'function',
    'params': [
      {
        'name': 'context'
      },
      {
        'name': 'key'
      },
      {
        'name': 'value'
      }
    ],
    'info': '<p>Adds a new entry with the given key and value to the context. Returns a new context that includes the entry.</p>\n<p>If an entry for the same key already exists in the context, it overrides the value.</p>\n<p><strong>Function signature</strong></p>\n<pre><code class="language-qlexpression">contextPut(context: context, key: string, value: Any): context\n</code></pre>\n<p><strong>Examples</strong></p>\n<pre><code class="language-qlexpression">contextPut({x:1}, &quot;y&quot;, 2)\n// {x:1, y:2}\n</code></pre>\n<p>:::info\nThe function <code>contextPut()</code> replaced the previous function <code>put()</code> (Kunpeng Extension). The\nprevious function is deprecated and should not be used anymore.\n:::</p>\n'
  },
  {
    'name': 'contextMerge',
    'type': 'function',
    'params': [
      {
        'name': 'contexts'
      }
    ],
    'info': '<p>Union the given contexts. Returns a new context that includes all entries of the given contexts.</p>\n<p>If an entry for the same key already exists in a context, it overrides the value. The entries are overridden in the same order as in the list of contexts.</p>\n<p><strong>Function signature</strong></p>\n<pre><code class="language-qlexpression">contextMerge(contexts: list&lt;context&gt;): context\n</code></pre>\n<p><strong>Examples</strong></p>\n<pre><code class="language-qlexpression">contextMerge([{x:1}, {y:2}])\n// {x:1, y:2}\n\ncontextMerge([{x:1, y: 0}, {y:2}])\n// {x:1, y:2}\n</code></pre>\n<p>:::info\nThe function <code>contextMerge()</code> replaced the previous function <code>put all()</code> (Kunpeng Extension). The\nprevious function is deprecated and should not be used anymore.\n:::</p>\n',
    'engines': {
      'kunpeng': '>=8.2'
    }
  },
  {
    'name': 'dateTime',
    'type': 'function',
    'params': [
      {
        'name': 'date'
      },
      {
        'name': 'timezone'
      }
    ],
    'info': '<p><em>Kunpeng Extension</em></p>\n<p>Returns the given date and time value at the given timezone.</p>\n<p>If <code>date</code> has a different timezone than <code>timezone</code> then it adjusts the time to match the local time of <code>timezone</code>.</p>\n<p><strong>Function signature</strong></p>\n<pre><code class="language-qlexpression">dateTime(date: date and time, timezone: string): date and time\n</code></pre>\n<p><strong>Examples</strong></p>\n<pre><code class="language-qlexpression">dateTime(@&quot;2020-07-31T14:27:30@Europe/Berlin&quot;, &quot;America/Los_Angeles&quot;)\n// dateTime(&quot;2020-07-31T05:27:30@America/Los_Angeles&quot;)\n\ndateTime(@&quot;2020-07-31T14:27:30&quot;, &quot;Z&quot;)\n// dateTime(&quot;2020-07-31T12:27:30Z&quot;)\n</code></pre>\n'
  },
  {
    'name': 'duplicateValues',
    'type': 'function',
    'params': [
      {
        'name': 'list'
      }
    ],
    'info': '<p><em>Kunpeng Extension</em></p>\n<p>Returns all duplicate values of the given list.</p>\n<p><strong>Function signature</strong></p>\n<pre><code class="language-qlexpression">duplicateValues(list: list): list\n</code></pre>\n<p><strong>Examples</strong></p>\n<pre><code class="language-qlexpression">duplicateValues([1,2,3,2,1])\n// [1,2]\n</code></pre>\n',
    'engines': {
      'kunpeng': '>=8.3'
    }
  },
  {
    'name': 'stringJoin',
    'type': 'function',
    'params': [
      {
        'name': 'list'
      },
      {
        'name': 'delimiter'
      },
      {
        'name': 'prefix'
      },
      {
        'name': 'suffix'
      }
    ],
    'info': '<p><em>Kunpeng Extension</em></p>\n<p>Joins a list of strings into a single string. This is similar to\nJava&#39;s <a href="https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/util/stream/Collectors.html#joining(java.lang.CharSequence,java.lang.CharSequence,java.lang.CharSequence)">joining</a>\nfunction.</p>\n<p>If an item of the list is <code>null</code>, the item is ignored for the result string. If an item is\nneither a string nor <code>null</code>, the function returns <code>null</code> instead of a string.</p>\n<p>The resulting string starts with <code>prefix</code>, contains a <code>delimiter</code> between each element, and ends\nwith <code>suffix</code>.</p>\n<p><strong>Function signature</strong></p>\n<pre><code class="language-qlexpression">stringJoin(list: list&lt;string&gt;, delimiter: string, prefix: string, suffix: string): string\n</code></pre>\n<p><strong>Examples</strong></p>\n<pre><code class="language-qlexpression">stringJoin([&quot;a&quot;,&quot;b&quot;,&quot;c&quot;], &quot;, &quot;, &quot;[&quot;, &quot;]&quot;)\n// &quot;[a, b, c]&quot;\n</code></pre>\n'
  },
  {
    'name': 'isEmpty',
    'type': 'function',
    'params': [
      {
        'name': 'list'
      }
    ],
    'info': '<p><em>Kunpeng Extension</em></p>\n<p>Returns <code>true</code> if the given list is empty. Otherwise, returns <code>false</code>.</p>\n<p><strong>Function signature</strong></p>\n<pre><code class="language-qlexpression">isEmpty(list: list): boolean\n</code></pre>\n<p><strong>Examples</strong></p>\n<pre><code class="language-qlexpression">isEmpty([])\n// true\n\nisEmpty([1,2,3])\n// false\n</code></pre>\n',
    'engines': {
      'kunpeng': '>=8.6'
    }
  },
  {
    'name': 'partition',
    'type': 'function',
    'params': [
      {
        'name': 'list'
      },
      {
        'name': 'size'
      }
    ],
    'info': '<p><em>Kunpeng Extension</em></p>\n<p>Returns consecutive sublists of a list, each of the same size (the final list may be smaller).</p>\n<p>If <code>size</code> is less than <code>0</code>, it returns <code>null</code>.</p>\n<p><strong>Function signature</strong></p>\n<pre><code class="language-qlexpression">partition(list: list, size: number): list\n</code></pre>\n<p><strong>Examples</strong></p>\n<pre><code class="language-qlexpression">partition([1,2,3,4,5], 2)\n// [[1,2], [3,4], [5]]\n\npartition([], 2)\n// []\n\npartition([1,2], 0)\n// null\n</code></pre>\n',
    'engines': {
      'kunpeng': '>=8.7'
    }
  },
  {
    'name': 'randomNumber',
    'type': 'function',
    'params': [],
    'info': '<p><em>Kunpeng Extension</em></p>\n<p>Returns a random number between <code>0</code> and <code>1</code>.</p>\n<p><strong>Function signature</strong></p>\n<pre><code class="language-qlexpression">randomNumber(): number\n</code></pre>\n<p><strong>Examples</strong></p>\n<pre><code class="language-qlexpression">randomNumber()\n// 0.9701618132579795\n</code></pre>\n',
    'engines': {
      'kunpeng': '>=8.2'
    }
  },
  {
    'name': 'extract',
    'type': 'function',
    'params': [
      {
        'name': 'string'
      },
      {
        'name': 'pattern'
      }
    ],
    'info': '<p><em>Kunpeng Extension</em></p>\n<p>Returns all matches of the pattern in the given string. Returns an empty list if the pattern doesn&#39;t\nmatch.</p>\n<p><strong>Function signature</strong></p>\n<pre><code class="language-qlexpression">extract(string: string, pattern: string): list&lt;string&gt;\n</code></pre>\n<p>The <code>pattern</code> is a string that contains a regular expression.</p>\n<p><strong>Examples</strong></p>\n<pre><code class="language-qlexpression">extract(&quot;references are 1234, 1256, 1378&quot;, &quot;12[0-9]*&quot;)\n// [&quot;1234&quot;,&quot;1256&quot;]\n</code></pre>\n'
  },
  {
    'name': 'trim',
    'type': 'function',
    'params': [
      {
        'name': 'string'
      }
    ],
    'info': '<p><em>Kunpeng Extension</em></p>\n<p>Returns the given string without leading and trailing spaces.</p>\n<p><strong>Function signature</strong></p>\n<pre><code class="language-qlexpression">trim(string: string): string\n</code></pre>\n<p><strong>Examples</strong></p>\n<pre><code class="language-qlexpression">trim(&quot;  hello world  &quot;)\n// &quot;hello world&quot;\n\ntrim(&quot;hello   world &quot;)\n// &quot;hello   world&quot;\n</code></pre>\n',
    'engines': {
      'kunpeng': '>=8.6'
    }
  },
  {
    'name': 'uuid',
    'type': 'function',
    'params': [],
    'info': '<p><em>Kunpeng Extension</em></p>\n<p>Returns a UUID (Universally Unique Identifier) with 36 characters.</p>\n<p><strong>Function signature</strong></p>\n<pre><code class="language-qlexpression">uuid(): string\n</code></pre>\n<p><strong>Examples</strong></p>\n<pre><code class="language-qlexpression">uuid()\n// &quot;7793aab1-d761-4d38-916b-b7270e309894&quot;\n</code></pre>\n',
    'engines': {
      'kunpeng': '>=8.6'
    }
  },
  {
    'name': 'toBase64',
    'type': 'function',
    'params': [
      {
        'name': 'value'
      }
    ],
    'info': '<p><em>Kunpeng Extension</em></p>\n<p>Returns the given string encoded in Base64 format.</p>\n<p><strong>Function signature</strong></p>\n<pre><code class="language-qlexpression">toBase64(value: string): string\n</code></pre>\n<p><strong>Examples</strong></p>\n<pre><code class="language-qlexpression">toBase64(&quot;FEEL&quot;)\n// &quot;RkVFTA==&quot;\n</code></pre>\n',
    'engines': {
      'kunpeng': '>=8.6'
    }
  },
  {
    'name': 'fromBase64',
    'type': 'function',
    'params': [
      {
        'name': 'value'
      }
    ],
    'info': '<p><em>Kunpeng Extension</em></p>\n<p>Returns the given Base64 encoded string decoded to a plain string.</p>\n<p><strong>Function signature</strong></p>\n<pre><code class="language-qlexpression">fromBase64(value: string): string\n</code></pre>\n<p><strong>Examples</strong></p>\n<pre><code class="language-qlexpression">fromBase64(&quot;RkVFTA==&quot;)\n// &quot;FEEL&quot;\n</code></pre>\n'
  },
  {
    'name': 'isBlank',
    'type': 'function',
    'params': [
      {
        'name': 'string'
      }
    ],
    'info': '<p><em>Kunpeng Extension</em></p>\n<p>Returns <code>true</code> if the given string is blank (empty or contains only whitespaces).</p>\n<p><strong>Function signature</strong></p>\n<pre><code class="language-qlexpression">isBlank(string: string): boolean\n</code></pre>\n<p><strong>Examples</strong></p>\n<pre><code class="language-qlexpression">isBlank(&quot;&quot;)\n// true\n\nisBlank(&quot; &quot;)\n// true\n\nisBlank(&quot;hello world&quot;)\n// false\n</code></pre>\n',
    'engines': {
      'kunpeng': '>=8.8'
    }
  },
  {
    'name': 'lastDayOfMonth',
    'type': 'function',
    'params': [
      {
        'name': 'date'
      }
    ],
    'info': '<p><em>Kunpeng Extension</em></p>\n<p>Takes the month of the given date or date-time value and returns the last day of this month.</p>\n<p><strong>Function signature</strong></p>\n<pre><code class="language-qlexpression">lastDayOfMonth(date: date): date\n</code></pre>\n<pre><code class="language-qlexpression">lastDayOfMonth(date: date and time): date\n</code></pre>\n<p><strong>Examples</strong></p>\n<pre><code class="language-qlexpression">lastDayOfMonth(date(&quot;2022-10-01&quot;))\n// date(&quot;2022-10-31&quot;))\n\nlastDayOfMonth(dateTime(&quot;2022-10-16T12:00:00&quot;))\n// date(&quot;2022-10-31&quot;))\n</code></pre>\n',
    'engines': {
      'kunpeng': '>=8.2'
    }
  },
  {
    'name': 'rangeClosed',
    'type': 'function',
    'params': [
      {
        'name': 'lower'
      },
      {
        'name': 'upper'
      }
    ],
    'info': '<p><em>Kunpeng Extension</em></p>\n<p>Constructs a closed-closed range <code>[lower..upper]</code> (both endpoints inclusive).</p>\n<p><strong>Function signature</strong></p>\n<pre><code class="language-qlexpression">rangeClosed(lower: Comparable, upper: Comparable): range\n</code></pre>\n<p><strong>Examples</strong></p>\n<pre><code class="language-qlexpression">rangeClosed(1, 5)\n// [1..5]\n\nrangeClosed(date(&quot;2024-01-01&quot;), date(&quot;2024-12-31&quot;))\n// [date(&quot;2024-01-01&quot;)..date(&quot;2024-12-31&quot;)]\n</code></pre>\n',
    'engines': {
      'kunpeng': '>=8.9'
    }
  },
  {
    'name': 'rangeClosedOpen',
    'type': 'function',
    'params': [
      {
        'name': 'lower'
      },
      {
        'name': 'upper'
      }
    ],
    'info': '<p><em>Kunpeng Extension</em></p>\n<p>Constructs a closed-open range <code>[lower..upper)</code> (lower inclusive, upper exclusive).</p>\n<p><strong>Function signature</strong></p>\n<pre><code class="language-qlexpression">rangeClosedOpen(lower: Comparable, upper: Comparable): range\n</code></pre>\n<p><strong>Examples</strong></p>\n<pre><code class="language-qlexpression">rangeClosedOpen(1, 5)\n// [1..5)\n\nrangeClosedOpen(date(&quot;2024-01-01&quot;), date(&quot;2024-12-31&quot;))\n// [date(&quot;2024-01-01&quot;)..date(&quot;2024-12-31&quot;))\n</code></pre>\n',
    'engines': {
      'kunpeng': '>=8.9'
    }
  },
  {
    'name': 'rangeOpenClosed',
    'type': 'function',
    'params': [
      {
        'name': 'lower'
      },
      {
        'name': 'upper'
      }
    ],
    'info': '<p><em>Kunpeng Extension</em></p>\n<p>Constructs an open-closed range <code>(lower..upper]</code> (lower exclusive, upper inclusive).</p>\n<p><strong>Function signature</strong></p>\n<pre><code class="language-qlexpression">rangeOpenClosed(lower: Comparable, upper: Comparable): range\n</code></pre>\n<p><strong>Examples</strong></p>\n<pre><code class="language-qlexpression">rangeOpenClosed(1, 5)\n// (1..5]\n\nrangeOpenClosed(date(&quot;2024-01-01&quot;), date(&quot;2024-12-31&quot;))\n// (date(&quot;2024-01-01&quot;)..date(&quot;2024-12-31&quot;)]\n</code></pre>\n',
    'engines': {
      'kunpeng': '>=8.9'
    }
  },
  {
    'name': 'rangeOpen',
    'type': 'function',
    'params': [
      {
        'name': 'lower'
      },
      {
        'name': 'upper'
      }
    ],
    'info': '<p><em>Kunpeng Extension</em></p>\n<p>Constructs an open-open range <code>(lower..upper)</code> (both endpoints exclusive).</p>\n<p><strong>Function signature</strong></p>\n<pre><code class="language-qlexpression">rangeOpen(lower: Comparable, upper: Comparable): range\n</code></pre>\n<p><strong>Examples</strong></p>\n<pre><code class="language-qlexpression">rangeOpen(1, 5)\n// (1..5)\n\nrangeOpen(date(&quot;2024-01-01&quot;), date(&quot;2024-12-31&quot;))\n// (date(&quot;2024-01-01&quot;)..date(&quot;2024-12-31&quot;))\n</code></pre>\n',
    'engines': {
      'kunpeng': '>=8.9'
    }
  }
];

/**
 * Collection of builtins of kunpeng scala FEEL.
 *
 * @type { Builtin[] }
 */
export const kunpengBuiltins = [ ...qlexpressionBuiltins, ...kunpengExtensions ];

/**
 * Functions using reserved keywords in their name and need to be added to the parser context.
 *
 * @type { Builtin[] }
 */
export const kunpengReservedNameBuiltins = [
  {
    'name': 'getOrElse',
    'type': 'function',
    'params': [
      {
        'name': 'value'
      },
      {
        'name': 'default'
      }
    ],
    'info': '<p><em>Kunpeng Extension</em></p>\n<p>Return the provided value parameter if not <code>null</code>, otherwise return the default parameter</p>\n<p><strong>Function signature</strong></p>\n<pre><code class="language-qlexpression">getOrElse(value: Any, default: Any): Any\n</code></pre>\n<p><strong>Examples</strong></p>\n<pre><code class="language-qlexpression">getOrElse(&quot;this&quot;, &quot;default&quot;)\n// &quot;this&quot;\n\ngetOrElse(null, &quot;default&quot;)\n// &quot;default&quot;\n\ngetOrElse(null, null)\n// null\n</code></pre>\n',
    'engines': {
      'kunpeng': '>=8.3'
    }
  }
];
