// ERROR_TYPES 镜像，与 @kunpeng/bpmnlint-plugin-kunpeng-compat/rules/utils/error-types
// 保持一致。本包（@kunpeng/linting）以 ESM 形式直接 import 此常量，避免跨包引用
// kunpeng-compat 的 CJS 源文件导致 Vite /@fs/ 无法识别 named export。
export const ERROR_TYPES = Object.freeze({
  CHILD_ELEMENT_OF_TYPE_REQUIRED: 'camunda.childElementOfTypeRequired',
  CHILD_ELEMENT_TYPE_NOT_ALLOWED: 'camunda.childElementTypeNotAllowed',
  CONNECTORS_PROPERTY_VALUE_NOT_ALLOWED: 'camunda.connectors.propertyValueNotAllowed',
  ELEMENT_COLLAPSED_NOT_ALLOWED: 'camunda.elementCollapsedNotAllowed',
  ELEMENT_MULTIPLE_NOT_ALLOWED: 'camunda.elementMultipleNotAllowed',
  ELEMENT_TYPE_NOT_ALLOWED: 'camunda.elementTypeNotAllowed',
  ELEMENT_PROPERTY_VALUE_DUPLICATED: 'camunda.elementPropertyValueDuplicated',
  EVENT_BASED_GATEWAY_TARGET_NOT_ALLOWED: 'camunda.eventBasedGatewayTargetNotAllowed',
  EXPRESSION_NOT_ALLOWED: 'camunda.expressionNotAllowed',
  EXPRESSION_REQUIRED: 'camunda.expressionRequired',
  EXPRESSION_VALUE_NOT_ALLOWED: 'camunda.expressionValueNotAllowed',
  EXTENSION_ELEMENT_NOT_ALLOWED: 'camunda.extensionElementNotAllowed',
  EXTENSION_ELEMENT_REQUIRED: 'camunda.extensionElementRequired',
  FEEL_EXPRESSION_INVALID: 'camunda.feelExpressionInvalid',
  FEEL_EXPRESSION_UNSUPPORTED_FUNCTION: 'camunda.feelExpressionUnsupportedFunction',
  LOOP_NOT_ALLOWED: 'camunda.loopNotAllowed',
  ATTACHED_TO_REF_ELEMENT_TYPE_NOT_ALLOWED: 'camunda.attachedToRefElementTypeNotAllowed',
  PROPERTY_DEPENDENT_REQUIRED: 'camunda.propertyDependentRequired',
  PROPERTY_NOT_ALLOWED: 'camunda.propertyNotAllowed',
  PROPERTY_DEPRECATED: 'camunda.propertyDeprecated',
  PROPERTY_REQUIRED: 'camunda.propertyRequired',
  PROPERTY_TYPE_NOT_ALLOWED: 'camunda.propertyTypeNotAllowed',
  PROPERTY_VALUE_DUPLICATED: 'camunda.propertyValueDuplicated',
  PROPERTY_VALUES_DUPLICATED: 'camunda.propertiesValuesDuplicated',
  PROPERTY_VALUE_NOT_ALLOWED: 'camunda.propertyValueNotAllowed',
  PROPERTY_VALUE_REQUIRED: 'camunda.propertyValueRequired',
  SECRET_EXPRESSION_FORMAT_DEPRECATED: 'camunda.secretExpressionFormatDeprecated',
  AGENT_FEEL_FUNCTION_NAME_INVALID: 'camunda.agentFeelFunctionNameInvalid',
  AGENT_FEEL_KEY_MISSING: 'camunda.agentFeelKeyMissing',
  AGENT_FEEL_KEY_TYPE_INVALID: 'camunda.agentFeelKeyTypeInvalid',
  AGENT_FEEL_KEY_PREFIX_MISSING: 'camunda.agentFeelKeyPrefixMissing',
  AGENT_FEEL_DESCRIPTION_TYPE_INVALID: 'camunda.agentFeelDescriptionTypeInvalid',
  AGENT_FEEL_WRONG_CONTEXT: 'camunda.agentFeelWrongContext',
  AGENT_FEEL_KEY_SEGMENTS_INVALID: 'camunda.agentFeelKeySegmentsInvalid',
  AGENT_FEEL_KEY_DUPLICATE: 'camunda.agentFeelKeyDuplicate',
  AGENT_FEEL_NON_ENTRY_ELEMENT: 'camunda.agentFeelNonEntryElement',
  AGENT_TOOL_OUTPUT_KEY_INVALID: 'camunda.agentToolOutputKeyInvalid',
  AGENT_TOOL_OUTPUT_KEY_CASING_INVALID: 'camunda.agentToolOutputKeyCasingInvalid',
  AGENT_TOOL_OUTPUT_KEY_OVERWRITE: 'camunda.agentToolOutputKeyOverwrite',
  AGENT_TOOL_RESULT_MISSING: 'camunda.agentToolResultMissing',
  AGENT_TOOL_DOCUMENTATION_MISSING: 'camunda.agentToolDocumentationMissing',
});
